# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: localai
  namespace: localai
spec:
  interval: 1m0s
  path: ./apps/data-science/localai/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
