---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nvidia-gpu-operator
  namespace: nvidia-gpu-operator
spec:
  interval: 1h0m0s
  path: ./cluster/addons/nvidia-gpu-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  timeout: 3m0s
  wait: true
