---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-admin-password
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgD1VDFA6pWwfcuyJ1cHkHzVeEwRoPe8DOCAWfgl9DFB8LyvPrT0dW4AE7JI/l1TLaUe0tcUeeKOkZAHAHj6N36k7Sjf5bwDvwQGd40xjKp0ctBPIfSCo6Bgfv+E5DQcM+tK0O0aZvVFMfqCXEjW4FeKfBeBH3R0SwHfdT53wD/gsxGiUyYUBupuP0oSjVxGlidg5DG8UTUYaRHEuvU9NoU+wVSXSglDHsrO46AnkkKOuowBLn/Hc68CF5dpB3BYeCtUzXUmJqtACmwnG2Lw2C/kfkkTxsXSnNwv4+vBTf/0ozolNNPRoJpc9RQGHmQm2Q43yEC5OzGpPqS4RUWMbCVXif+t+rX7Qsh7e34gsTs5wCj13n+SqHh70tyQ6P0yCfJZc2BEB4HIC2UF4kojHyIMErMvGL7rxIqAhoo4F4BRCEgn7FzkBzIt0ZQQwmjUCUILnbuzZ6zfWLVUJf6QzB6UkAOgpAYVZFksvyUWM4ntKxeD5RAlq+ZSuqr7yF81k1s9xyrNvBfKLPJz8Y3PQN4+zxWCdymaxbgzNoB1pOGc/UyiKZ3McpAELqccO4xODS7vLWn9SIPemry6odnqal0jBu4aT3sUu4RBqqLdEp/YXsNjv9Qn3sHfoVaTB6PwmnCieHKCz9yZiG3536kui9s4Zb+o+ZaOLJ3ffm1CfPZg41g8/s/BnsxlAEurpfduEdM9k81VqWVIM6qxHynADHGaQCI0MP48g0g8nOcpyPLfaji8iz6Nqkt7yHXcDg==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-admin-password
      namespace: harbor
