---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-gpu-operator
  namespace: nvidia-gpu-operator
spec:
  chart:
    spec:
      chart: gpu-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nvidia
  interval: 1m0s
  timeout: 30m
  values:
    driver:
      enabled: "true"
      nvidiaDriverCRD:
        enabled: "true"
        # nodeSelector:
        #   kubernetes.io/hostname: bigrig
    operator:
      defaultRuntime: containerd
    toolkit:
      enabled: "true"
      env:
      - name: CONTAINERD_CONFIG
        value: /var/snap/microk8s/current/args/containerd-template.toml
      - name: CONTAINERD_SOCKET
        value: /var/snap/microk8s/common/run/containerd.sock
      - name: CONTAINERD_SET_AS_DEFAULT
        value: "1"
    # validator:
    #   plugin:
    #     env:
    #       - name: WITH_WORKLOAD
    #         value: "false"
