kubectl apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:jammy
        command: ["sleep", "infinity"]
        volumeMounts:
        - name: the-goods
          mountPath: /old
        - name: thegoods
          mountPath: /new
      volumes:
      - name: the-goods
        persistentVolumeClaim:
          claimName: the-goods
      - name: thegoods
        persistentVolumeClaim:
          claimName: thegoods
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thegoods
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 5000Gi
EOF