clusterName: rook-ceph-cluster
toolbox:
  enabled: true
  containerSecurityContext:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
cephClusterSpec:
  storage:
    # config:
    #   osdsPerDevice: 3
    nodes:
      - name: bigrig
        devices: # specific devices to use for storage can be specified for each node
          - name: "/dev/sdb"
      - name: oppenheimer
        devices:
          # - name: "/dev/sdb"
          - name: "/dev/sdc"
cephFileSystemVolumeSnapshotClass:
  enabled: false
cephBlockPools:
- name: ceph-blockpool
  storageClass:
    isDefault: false
    enabled: false
cephFileSystems:
- name: ceph-filesystem
  storageClass:
    name: cephfs