---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
spec:
  chart:
    spec:
      chart: airflow
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
  interval: 1h0m0s
  releaseName: airflow
  values:
    createUserJob:
      useHelmHooks: false
      applyCustomEnv: false
    migrateDatabaseJob:
      useHelmHooks: false
      applyCustomEnv: false
    postgresql:
      enabled: false
    data:
      metadataSecretName: airflow-database
