---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webserver-secret
  namespace: airflow
spec:
  encryptedData:
    webserver-secret-key: AgCq2CZjEVdRc4adMmA8qFACw2i6LciqSNR+6UqQ2cv0eMOEpoZydyJVrfhY6qMIhTRSFK6clsJsHqjU5HgeLOLehWs6DZUcbRrkvmud4y5LdWmzMj0CCSdll3Ni0iBuDISIZYYtH1IPoKywdbe6oFHCOWomMy+De3VLb6iP3BH6IXTkAvC/j9tnIRWN2XrbccnBJptuudYeuK+qEMNepfcb9qyTwiPcrhpZKI2kMmu/eKWAnVEm9aoE1JYyl+pXYmNpJfwOFgc79Ek2lgnfWDs7z+3UvAXmN5J53Axnm93T6xSbnjV6KZLKdgDNalzUdzl53/M/REy9waRk38RgyHe5SBCimvAq1vbKJkaNy8TE/rmOXrjaFkXEhtcmx0uiCrneVmOhfx4QaSrwmDqBfPyRSDkSVZnF75YliNzlGq/uG6q+eYckBcJs+CR9uUSTpyrWTX5CcIXi9XL2Z6ixuSyuLVkrsfOllB9wPtLuEiMVb5fewdLzJl/7yp/xWPxKaeYjp8D5SkGmSe1r+luGAbTlbLJKX5QZKMFBH+xRpZ+EZ7hu9ZHuft9cHmtn/9hvQthdEfTOzsWlqc9NyYsAFldl5RtuoIhSCRrh5XXCFnF9G3oMGL8UKMV+YUrWk6M9XsjQFy74ilxsW6PpaiMFTgwMU+mDkQAG05eQWOBLPKux5HOIXRLAEnpKsBsSBaqWvD+wJXavg1TIisLLG8kGRkyg/c2BjeeRw96HGOeOe4kNxpkuTUyPLg5Zl8RehA==
  template:
    metadata:
      creationTimestamp: null
      name: webserver-secret
      namespace: airflow
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-password
  namespace: airflow
spec:
  encryptedData:
    POSTGRES_DB: AgDnXOHvLu+dqbd6BP6jGmxBzayvpa4N4sKIn++Aia3z+dXF6fEHvsExg7IcB++GeuhMLpqGo1sT70DNc/gwr/YteDrybpV+ExoS/Wwi04QbQELDrMw79g3x0xvglH4FEx24oGxyfUILigXtdb+J7hEt8n3S+VlqJtmN+1WoSG3rWsa09yce1cQSLmKLeVvbflN5a3lrOcpeYhOWO1DJwiLORXeizK9iCuN0P1m2rJs63v4BC9mJnvpqH944quFgvtqqlaLVqarVFMs3ugdMXEVO4OS9s/O8jmUFO/Ie9u4nUWeTvFRCBhGn4Zr4Sg6gzyN1mnsXFl5qEOpmVu45h1ELvPA3C7obu5KxrtsZeFUlW5fhd/k/RsPVY0VDJiXOzSiTyl2CVm92QEt9qOCtlevP1zA4rE6PXvhpH+gUsFiSWvOyan9HtjyzjA8guxSuorWFbQRP/3akgzoFhK5HUvflCrwlWRjgOo9Ezt7j/pqeWm+MRsKzNPl7uDn4+Dz6WUmEcX3DltiI8XulF7dGQ8bM+0eVxr3+X1Z6kkcm0xgZQ8+WuO9FSytre3eW/hp+4z6jHTbcJmq9RcIQxXhKxBp9IU5yAMUfzd8A7fIz5SlJj0susGW0aDnbBCQe1Whe053CVtvPCoUQ+vTqvjPxkZsR+qZMc7/zqb85NLdlsvg2LRGY28h/Uo46CnmPPe+hry0AM2btkBB9
    POSTGRES_PASSWORD: AgCZsz6ybCV8umnR3s71Uo+ZKucBr9kDHPKc6K28gCoCD4V8DtEGz80OdqG4Txo6FYILkkC7UNt+idjKR5d53Kkm1ugKX6vJhsrx4l8vMQBcchg9mF7evx4+fRYPBYLXX39nufJO/9GsZbTyEAGol3MswxZTi4AeF2Ytj+SJLrr0zUvFGSJy6X1ceQQ+PP/8YcSBD4PVZLH/3DPXUzzLo3o/N1IsFdcgNAq8bx8wNS0OUNP4owXlYEgRl3f4/wIH3mkbuhZotoBbPo09SmPTrz/Ami56AAAxjjcF347gqOaQJHJAVYpz2YhD3LJ6IXkYMlHFMndrDUBgq7vG+PJFyn17scdRS+XZMCscvhsf6O14jseGuEDfRsM0Lv1KfT96prlmD4SsCz1BB2KGtazSAPXCsI79hrfW0amUw5/Zz2MMGz2o2DVjPVRz8KGmlxbD2XF6GGpqAoYadpvB8K8VDDIozg7xYjYJvHVHp1NAHr48K2nNegrqzgVj0E1WYgpY8OFl/r/wID53OQUQatmDAusnsPzw0Ix3ttHdiSs7SrlDTsQwnAitt2sl9ItwJVrSuc8OqGYTzN8PEuBf6ExuqTW90XwvnhYvIXensocIyvH+FRkbMTZfyL0eBTShPR2x6FLbizRRxTqwxWzvHoPtR2ezO3tkjkWuH4FoqrcczlDLl3Y3SMG0/kjxdQgUv1Tcf4T+bYTDLW1S1mbS2CK3y2CgZ0NRrdO4TG19LS9QhXM+JR+TWYXPk6cJKWYOcg==
    POSTGRES_USER: AgBJJMAKSL3XILfkgiKbtnKdJeRAROOQGpknXhvJ6eS/qS/rIdXE0wz3FY/daI32nzhHzzBcIDfrnhcw9JZYxneX0K7quyLxUvqELiQALtWeuDDnC8Yt5Uih5hmPcR78fg0yw3gLhL0r9CtNz0VT6owCO/aYVBA1HB+OcbJZilTRBVY7Q0BD+w1peHVsDVL4NLqnYos0XZlV3ghDHCOFzC8pmVCEvWITz9SO4JK/RxwROzaIqYYkqq7I9CHkepPdjvcJSj5N4ieimf24Mi0vuUQQsaf9oyHNrAGDCvcsXOM9r9mqBbuSlATyEbDljQSHB1xeohI/U4DzrQIUi4+h6+XC6E6UQTSWv/5frA58BrhZ82Oin8scssbK7HRM6yaqQ+hQoO0ZM3MKxA06ShoGVdprmtRF5mwITihZMvpwUMZLIrPwiSEb7/ERQXqbFuBX5lhEmaRIXW9cYeranEiijnLtlu16E5hPepB4FH7s2QNSmlh43npWaMsMPJrO6z1lwxVxvguGSFUCIMRaEpXoDoNGwS6JDa7Oo9PhRU8pnrIIwcSzkaOoMr0Y5NSxJlwoqFh/M3g9ae+yNX0Lya+TZbM86AhueZRaxjJgYpWRLqjqAfyemHYQ+KTAVkjN9t/rrh0ugX9d8sS4m/c7onD0u7hBTgTTdHo3fsMwd6FHRICclvUirrt9t5oWcgtL8du/qRFKZfBeZx6N
  template:
    metadata:
      name: postgres-password
      namespace: airflow
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-database
  namespace: airflow
spec:
  encryptedData:
    connection: AgBK/ETSCO0NMk096ADUpY1EH8iUTkhz1xvYyc4xVxuuM6UWfwBhbARKuNlYTmlG2lQTFaEwsVrqPeDGjZelvr+eRyEZ+wfFvLIttam8znazlZyRSVj4G+Tcljo1tKDIpfNVAvOXN27GiP5YzjiYPo7fEXOMP5yexb5tVH16CtDj6fgBnwDEf807Fq9bpv93+pHMnc7s4+ioluiwu0KDERCNhipnB+bsplNbJY/Kp2Km9xL2V2rmM38HQoFC33z9mqabUTPMsVPQJ1Qm3DF0qsyf97PHk/a5MaKkIWz4XKIUkS7AtLd2XGhiMH7P+d8695ZAVroN8feSOqohZfSb9vR820JNC1+UWEbVWv5TslV6GSvpADjArWjF3NQBVKsxTc1fyaIZGZHKW9SRTXtDt2mSQpPeUobuGjCKOUaS0Ohkk8Ey0XzRY4Ucw7Bqr0ML70A3KFtwTB0Oa9MsNeYmzNjX3FAo3fDe3esqkNK8ZdO5Cxryl6mPVPDPx0KFv96mQ9nC12GknTtSx5WoxHTjzrh4VJtnusMHbXJH6DiOSVvK40fNR4+iLNYw5ss+Mitcf11eQZR7eyzDiXlxLvMp/cvDNBFqA0rcUFnm/hCkUfkEzsu0jtIxfNptdl1iPWYJN8qkbQAwW/HWDQzp5wxV/fd02k1AilOfYAxTsCBylB/KpxX8BcwZF42I6vPGpKdeyGkXGrYr1r/N1O3M/+giIduhqyhPcuEizltdJv/FqEna5Vj9qiMsoRaKOP0+ZpnHB4dfbQ/OSMeAsauK3ZtPDa6QmmovC72B2v771B8zH9Ilteg8epGSOpSopI2QYefDilpKP4WDBSoSXDDI8L1Lp5CBVCw+daIoC29LwXWl1Bovyl3lL8s23KhSRHggAz1LbhktdBOv584cUg==
  template:
    metadata:
      name: airflow-database
      namespace: airflow
