apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins-tls
  namespace: jenkins
spec:
  secretName: jenkins-tls
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  duration: 8760h # 365d
  renewBefore: 360h # 15d
  isCA: false
  issuerRef:
    name: homelab-issuer
    kind: ClusterIssuer
