apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emby-ingress
spec:
  rules:
  - host: emby.internal
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: emby
            port:
              number: 8096