---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
  interval: 1h0m0s
  values:
    ingressClass:
      enabled: true
      isDefaultClass: false
    deployment:
      kind: DaemonSet
    # ingressRoute:
      # dashboard:
      #   enabled: true
      #   entryPoints:
      #     - web
      #     - websecure
    certResolvers:
      letsencrypt:
        email: support@doctor-ew.com
        storage: /data/acme.json
        httpChallenge:
          # used during the challenge
          entryPoint: web
      letsencrypt-staging:
        email: support@doctor-ew.com
        storage: /data/acme.json
        caserver: https://acme-staging-v02.api.letsencrypt.org/directory
        httpChallenge:
          # used during the challenge
          entryPoint: web