kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  labels:
    app: whoami

spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - name: web
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami

spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      targetPort: web

  selector:
    app: whoami
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-notls
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami
            port:
              # name: web
              number: 80
    host: whoami.internal
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: whoami-tls
#   annotations:
#     traefik.ingress.kubernetes.io/router.entrypoints: websecure
#     traefik.ingress.kubernetes.io/router.tls: "true"
#     # traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: whoami
#             port:
#               name: web
#     host: whoami.internal
#   tls:
#   - hosts:
#     - whoami.internal
    # secretName: whoami-tls
# ---
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: whoami-notls
#   namespace: default
# spec:
#   entryPoints:
#     - web
#   routes:
#   - match: Host(`whoami.internal`) && PathPrefix(`/`)
#     kind: Rule
#     services:
#     - name: whoami
#       port: 80

# ---
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: whoami-tls
#   namespace: default
# spec:
#   entryPoints:
#     - websecure
#   routes:
#   - match: Host(`whoami.internal`) && PathPrefix(`/`)
#     kind: Rule
#     services:
#     - name: whoami
#       port: 80
#   tls: {}
