nextcloud:
  configs:
    mycustom.config.php: |
      <?php
      $CONFIG = array(
        'trusted_proxies' => array('10.0.0.0/8'),
        'default_phone_region' => 'US',
        'maintenance_window_start' => 1,
        );
