---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  chart:
    spec:
      chart: homepage
      sourceRef:
        kind: HelmRepository
        name: jameswynn
  interval: 1h0m0s
  targetNamespace: homepage
  values:
    serviceAccount:
      create: true
    ingress:
      main:
        enabled: true
        labels:
          # This label will enable discover of this deployment in Homepage
          gethomepage.dev/enabled: "true"
        # annotations:
        #   # These annotations will configure how this deployment is shown in Homepage
        #   gethomepage.dev/name: "Homepage"
        #   gethomepage.dev/description: "A modern, secure, highly customizable application dashboard."
        #   gethomepage.dev/group: "A New Group"
        #   gethomepage.dev/icon: "homepage.png"
        ingressClassName: "traefik"
        hosts:
          - host: &host "homepage.internal"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: selfsigned-tls
