# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: vectoradd
# spec:
#   restartPolicy: OnFailure
#   containers:
#   - name: vectoradd
#     image: nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2
#     # resources:
#     #   limits:
#     #     nvidia.com/gpu: 1
#     env:
#     - name: NVIDIA_VISIBLE_DEVICES
#       value: all
#     - name: NVIDIA_DRIVER_CAPABILITIES
#       value: all
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  restartPolicy: OnFailure
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep infinity']
    resources:
      limits:
        nvidia.com/gpu: 1
    env:
    - name: NVIDIA_VISIBLE_DEVICES
      value: all
    - name: NVIDIA_DRIVER_CAPABILITIES
      value: all