# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: cert-manager-egress
#   namespace: cert-manager
# spec:
#   podSelector:
#     matchLabels:
#       app: cert-manager
#   policyTypes:
#     - Egress
#   egress:
#     - to:
#         - ipBlock:
#             cidr: 0.0.0.0/0
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: cert-manager-ingress
#   namespace: cert-manager
# spec:
#   podSelector:
#     matchLabels:
#       app: cert-manager
#   policyTypes:
#     - Ingress
#   ingress:
#     - from:
#         - ipBlock:
#             cidr: 0.0.0.0/0
#       ports:
#         - protocol: TCP
#           port: 80
#         - protocol: TCP
#           port: 443
#         - protocol: TCP
#           port: 53
#         - protocol: UDP
#           port: 53
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: default-deny-ingress
# spec:
#   podSelector: {}
#   policyTypes:
#   - Ingress
# ---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-ingress
  namespace: metallb-system
spec:
  podSelector: {}
  ingress:
  - {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-egress
  namespace: metallb-system
spec:
  podSelector: {}
  egress:
  - {}
  policyTypes:
  - Egress
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: default-deny-egress
# spec:
#   podSelector: {}
#   policyTypes:
#   - Egress
