apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: airflow
spec:
  project: default
  source:
    chart: airflow
    repoURL: https://airflow.apache.org
    helm:
      releaseName: sealed-secrets
      valuesObject:
        config:
          core:
            load_examples: true
        images:
          airflow:
            repository: apache/airflow
        webserver:
          service:
            type: LoadBalancer
        webserverSecretKeySecretName: airflow-auth
        workers:
          env:
          - name: NVIDIA_VISIBLE_DEVICES
            value: all
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: all
          waitForMigrations:
            enabled: true
        createUserJob:
          useHelmHooks: false
          applyCustomEnv: false
        migrateDatabaseJob:
          useHelmHooks: false
          applyCustomEnv: false
  destination:
    name: in-cluster
    namespace: kubeseal