FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04
USER root

# Install python and airflow
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    pip install "apache-airflow[celery]==2.9.1" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.9.1/constraints-3.8.txt"
    # how to install additional operators
    # pip install "apache-airflow==2.9.1" apache-airflow-providers-google==10.1.0
    