config:
  core:
    load_examples: true
webserver:
  service:
    type: LoadBalancer
# webserverSecretKeySecretName: airflow-auth
workers:
  env:
  - name: NVIDIA_VISIBLE_DEVICES
    value: all
  - name: NVIDIA_DRIVER_CAPABILITIES
    value: all
  waitForMigrations:
    enabled: true
images:
  airflow:
    repository: apache/airflow