---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  chart:
    spec:
      chart: ./charts/jellyfin
      sourceRef:
        kind: GitRepository
        name: jellyfin
        namespace: jellyfin
  interval: 1m0s
  values:
    service:
      type: ClusterIP
    persistence:
      config:
        enabled: true
        # storageClass: microk8s-hostpath
    # extraEnvVars:
    #   - name: NVIDIA_VISIBLE_DEVICES
    #     value: "all"
    #   - name: NVIDIA_DRIVER_CAPABILITIES
    #     value: "all"
    #   - name: DOTNET_SYSTEM_IO_DISABLEFILELOCKING
    #     value: "true"
    nodeSelector:
      kubernetes.io/hostname: "bigrig"
    extraVolumeMounts:
      - name: irma
        mountPath: /irma
    extraVolumes:
      - name: irma
        hostPath:
          path: /var/mnt/irma/media
