---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  chart:
    spec:
      chart: jellyfin
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jellyfin
  interval: 1m0s
  values:
    service:
      type: LoadBalancer
    persistence:
      config:
        enabled: true
      media:
        enabled: false
    extraEnvVars:
      - name: NVIDIA_VISIBLE_DEVICES
        value: "all"
      - name: NVIDIA_DRIVER_CAPABILITIES
        value: "all"
      - name: DOTNET_SYSTEM_IO_DISABLEFILELOCKING
        value: "true"
    # nodeSelector:
    #   kubernetes.io/hostname: "bigrig"
    volumeMounts:
      - name: cronenberg
        mountPath: /media
    volumes:
      - name: cronenberg
        nfs:
          server: 192.168.1.182
          path: /mnt/cronenberg
