apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: jellyseerr-config
  name: jellyseerr-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
