apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  storageClassName: cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu:24.04
    volumeMounts:
    - mountPath: "/test"
      name: test
  volumes:
  - name: test
    persistentVolumeClaim:
      claimName: test-pvc
---
