apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
  annotations:
    gethomepage.dev/description: Find Torrents
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Torrents
    gethomepage.dev/icon: prowlarr.png
    gethomepage.dev/name: Prowlarr
    cert-manager.io/cluster-issuer: homelab-issuer
    nginx.ingress.kubernetes.io/backend-protocol: https
spec:
  rules:
    - host: prowlarr.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prowlarr
                port:
                  number: 9696
  tls:
    - hosts:
        - prowlarr.internal
      secretName: homelab-tls-prowlarr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent
  annotations:
    gethomepage.dev/description: Download Torrents
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Torrents
    gethomepage.dev/icon: qbittorrent.png
    gethomepage.dev/name: qBittorrent
    cert-manager.io/cluster-issuer: homelab-issuer
spec:
  rules:
    - host: qbittorrent.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qbittorrent
                port:
                  number: 9091
  tls:
    - hosts:
        - qbittorrent.internal
      secretName: homelab-tls-qbittorrent
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  annotations:
    gethomepage.dev/description: Find Torrents Automatically
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Torrents
    gethomepage.dev/icon: sonarr.png
    gethomepage.dev/name: Sonarr
    cert-manager.io/cluster-issuer: homelab-issuer
spec:
  rules:
    - host: sonarr.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  number: 8989
  tls:
    - hosts:
        - sonarr.internal
      secretName: homelab-tls-sonarr