apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  type: LoadBalancer
  ports:
    - name: "9091"
      port: 9091
      targetPort: 9091
  selector:
    app: torrents
---
apiVersion: v1
kind: Service
metadata:
  name: stremio-service
  namespace: default
spec:
  selector:
    app: stremio
  ports:
    - name: http
      port: 11470
    - name: https
      port: 12470
  type: ClusterIP