---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stremio-htpasswd
  namespace: torrents
spec:
  encryptedData:
    htpasswd: AgBCS46/OLNs7nuBQNpxX0UlccVvIJGpSU8Smtrk3hI0C6s6En9SFanc13kBXDGRWGW3HNONLK2U3TBIfEdHUe3K05MccZqkq7S4Tfr9HGZzoylh5izNKtyYN5ifxl+JWRw7sxvMGWjf55f0tRXDa9DxTzDH8CosrTzxPQVfJVrI0tdxJhXvb0vdnVEULvldBXuzHpOpwifUYfXY5nXOo2MZsDGSUyki0S8sAqCxiqCcNw4H7TjL2Ki3mslhIIfCLInTnE5K/BRz/00eu5L9QM/qG8WajC/9k43sVPdkzT6dlzfBTM7AHtojieIDq0FVqpD9IlNQcuJPrr+gmoopIJnN+grilnxgITNYz1NKuhLMJiDyheewGtgdlOt8sNmskPMyWbZbns4026JzvAgxnbRUfKXr5I42I22sODz10eOGrY5Xq7OHCiJoNiGYzUA3tfC8VXd77XCS8niAIbf4uJwIteV4K87GvQmCWsLAbV7vYK3QiKUUbeSIZJcVoFZ+wFU8PQKRBN/mcjFXM5S2Z6P6UK+fCQP4vN8oZOurcp8w80bo+Axmwc0MZpn9uuzoGxDJYzttFWEhZ5TUXng2M+85vBE4QwIUvztNR09pxDH3ciBzVsvELEa2pnPDs/Pk2NAmX5Yh7ujI8KdNlnuCcHJuE0c/pcya98efPvQsf4Z8xLWl/oGjXdd1h4d/CQoPGzw/LOK/EQ3/7mnIrZkj85+h2LJXRPIwVV9KbyXAOK2Omac4wO12NbF8aldPcD7PBUdJMZRPGzpOvm6xfiW3reliqDVtXyB3M6oCiHfmNOdEIhtj8p38zbm1v6qY1S/J/i+/OvQjYYXUzs6uHxEW4DG1fDrBZ1ZN8U2Qi7BwIh7NRbZN4aYKFO4rwKQB6FA7m9LdG67JR8MGC20ui/i9VCtVPhT38TPF0JAZxTqTdWGHrluYVoQHiqPd/L3qJVLjTdLhT/5kb9tlIAyBZNuJaHvcLA5eKAfpU66LTuUTVLD0C7ZkIdcFJTFXqFg/K7dWkhHjd8JvqVP+cGH/+8VIb0dqf3LHAx0hthONGwICuOH+nnsWF8R6R92WTCCg8f8X7RSrqKecLkqOAQLWElvR6rzl/up0uo8qq2qi8W6q+duJSy2xZff1QdVjckLzrNMNoDwlv7Ip7ZzxOPZfWCL9ESCy80iM5gu9dKPIcmO4ixMkjAdCR3xnibFwX7DSKBFDCeV0jck4JPC83IVnK/xBu7NKzhKEaAqmwOW0IAVG2vygP2RQHmIxUEVtmuIeOgT/R7yiG3N7Fu7vPBWggfzlSXEuj7B+WOiYWRJYg1vWrca0L37yuIaAvg==
  template:
    metadata:
      name: stremio-htpasswd
      namespace: torrents
