---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard-config
  namespace: jellyfin
spec:
  encryptedData:
    wg0.conf: AgCDm1zfPr2OMT/c945Nb8QdI79FTu0GE6zCxOinbJvtd+5Q5SWiu9YYG/T9hefqML83SU6VNR41ymfjrCMD2l5TeX7Ocuj7mRBqbf6LQLTzp11QIOUbK9oFZTNmujieSryIpFpAnl6OiYgmwJXfQdyr63t91GT4FvXb3C5cORXa2XRxyS/xXrisFm5iM6bL2u/LPIDnGQ4oo+BX8HqBY4YR28hEQ78mZghvFQ1rtLgUfkMVPh9Al0A94BX81U6nIpCdrFlX3gewpdKuKgej+V14jf3g8XiY/Jmw4V93htpdwgavovUoq0RjwgQ1ll8Uq2e9p3QyKkyT+XvzYYtZYff57NpmPgRDByKdfLWMP1M/D0gi5NltFpvcdC0yCNwNy9OiunsBkRXV52iAYiTGeDAF2fxxA9sSc4cTtUJujlf3z4EwnKLNKn6vb5jlxYvOuX1qgaReO7ewpYPr7RRULD6s6eEdYtk/IwAeF7MAqBATW8Xisdo+du7EXxuKXvMPNEToCZV3rVGaPNoqWqxJutqoaLADqlXzmLJwbWvCxR0/aXS2TDXaWOWonZckRtjNewU93wZxqBB0XuR+EtHSvCWy9egcGR70gi3wl3XIpO72ocS55S2hEuWg8OpzQSRRdvD+tKcuivGqzztDbGf/CzkieP/aPVBudGPEgOfJZqPVxbSo5C8uokWzEFz6PpTHSM2iGrJp77nVkhdnohGYdFg9QcxE39huyHg2r1MSZP4vJoA04MtHgUsqjzqXXwrlfm8uLWuR4WWLAvWuQDkEfw28MRyEYi59BadZ3BljrhaqqjccUIAxSKyo1h5VZdJEHlwSE2UUv/hffbUjeE3yihZLlOIU1LSQRFWIhfIWy/dpxKR+JEbOxccxRlhb/P2N77oN/Q+g5YrT+/pq7/wxN47FTOE9rlG22ufTl/w7ju9Ac+OsYHzVfcnPy/j3t+lO6D1EdjLlvN1L7bTTu/bpgTUKJohfGgebdc8pfI1rjg4PgbWIdmLdkIoWUAkmfepYvRxDqnJBTVGtnJCKcpAg7vFdtlNmKJQeVEcsVBZPuExUloTCGY8S/gHuob7nJVGAuiSCsSEQrlYaKeJWR86Q+7sXhqgGIJDn8ngkaSFH7ughO9rzqu5OYsmx8FAk4f1IeD7F91VyZGP/
  template:
    metadata:
      creationTimestamp: null
      name: wireguard-config
      namespace: jellyfin
