---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard-config
  namespace: torrents
spec:
  encryptedData:
    wg0.conf: AgDgA4dkjjTx0oY5db846FOKJK02s0su6EVt7YR7V/Hr6wyJIxLFq/PHlOj3ekIbMMLjGLFwulqKIALoOvYEDhKtycEH4CYMecjo0thyu5XkY+4aQdYRZZb+lBFx0eviIXwxVoz/BUs26JpJWFvNCRom1+FBbmvpKh2PxgbF+oQoeIUPrGhYFgqz/yxaWI6jlqxe5mk1lYNVPvZXC307fUaU1q+TdRY10VypiimWZbnBiF/TtnEXbswuoOIYqSCozOoNE+b7QDHGeI40cF5TlOur7ekIyT5gFji28Od8dmgEZaTcnmNnHxLK1oJskKjrcEzNNXb757EFQNkdmibOgdMjhvMf1EtrNUnMh2k5ISx4TAeKfe+gdVqnTWaKtTfx1enTUtLfswxdh7OFDZEBf607BmGbMBSyoFbuZ2MO9TcOsEzU0IBMfNmPHrDIQIh7fdC/8b7MLrEroz43UkY7zlKw1tXiEe8NUR0fFpckc/Ub3WZnNeBo/oksPAfkCB8oQgDPHoYiiG4FzD6GVrptGHzgq7rtWDIizU4xl7lleBxsgWp1JChKcjqyFqFDgSHzpmyfq/nzwUSYxv1z/wioGX7DokkypO4EJSphTnY/L8qhKfLcmqYDcke8sFKOmpxe7f5Yxge+a8vPmiHjVxOwsU+8wSawIXjEPNwubC/5gk5pltU7FHBUca7zo1qLpOmRZfzVlBCfyAkCC14UBL5nU/BlLGPcVyUcAqWSaDE6oLh2nXmhza75vfMIPfJUM3s9hnsSY07Y098KYZM+xAuJnqNXVnzS325uNbIyWU/TSklmoX5UmOnJsCipuHETViVfJpTNMQ1OyUiY2NYBylBNoQrCASyW0/e7vamO/l4yfmMpT6qCLF9Tl57VQ46/+uOPb4NpPOWwFNGnEC0sOPmwPHXNU8w1vnt0JHlIi/zLD1o1Z3KMfBjfwoiZWWBmL+bXJSv4rsTVtAQ2haD9RjNbIv577nRAE11vzRgFrzoZ5d4DaPWrGX9uy7JHeHOq/K4vXeTm1jZvj19mYx1+8JhgX8xT5K5iXM9+md+/9lVxWl1nu8O4w1oodDs0zsTseRk1I+sHPihcI5CK/eOQKOozp2tZKymDErBxo5Q7tOb/h5RQgRA6wSIrB2ZMUl+M8JjkZuo6JsnbWTJHehfnoqY=
  template:
    metadata:
      creationTimestamp: null
      name: wireguard-config
      namespace: torrents
