---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard-config
  namespace: jellyfin
spec:
  encryptedData:
    wg0.conf: AgCVcsw5qekKMd017gr+PNfFymEK7wlYYCDVD66HY0mFDSDpKbHBbZjKk/ndVWU96GabZYn9G2av65CFF/5eNiEA9P9g8IBr+dMbfiWcC7MJyi3XhYXnvC4RJ3k+OG92D9tR/VN1in+aQ98e7Py6mH78C2UQRWFLK7LS26O8AtHtrciddb2uSaVMTo0ghUwca525Mn34PAQzbTeKrNsSb7yx22T8TChyDXKuiaq+1bW5LrKtd7tVN/f51zvKmh0MYKcuL8uVdfHFqU8vtr6bnnSMaF0qKXjwyfs9Sk6GRC561lFzDvVY7USSLHBN0Kj95PGchJVGJz0Nlmwt7DvsIcIZ8TuHfTQ7661b1fzfin4iEaILrcRiqjK9U/WwGeZ13+Cw1Do09SKnDyQIgGScUr225/bk7EVbEmJfFP2XF+4M2qbN5q+llXUhahsI7z4/lfYOd9xgTeDPH4W8uW0jMbnJitVWBT9xU5wZUmDdmfcTaLV7mMsgl1b3y3tesfFBThzHQUKxd205Jd1ElCE2KIq9en7i5k6dSNnIR3bDJEMKcHMDXz9JUirp4rf+FtLfxdU/68kBGNYT6uPB8LmEqOTsSWYTp7XDfyU4lDieud8KJ2P2uU6SX8A/s/ofJjgLJmhbR6B3Ts335jtqBeBT2JIqv6J6CGkl7ZKutC0NTO7sBsMPItzyV72WLX2T21hayDJRMZEvYTfe8MNRABSG4f/7i9OFMzIdxd9tDKmK10AafHGhzG/nvVCnV5gzOxzTWmGxHVLBXkF/N5BgxQFHeH6JG/Mb47kam5GTztvAAUzNmIJzuplSfL2pUPO0QYTCBkJyG74lZ5rmzMmgwSWIcoxqFjgXbTXTHgF1JVIxwEl2ShyZ9/ktEXRhG6n98xPzPgG9N1CbJCWWBLFBmfRokZXH17QV62hHYQIY3mMK7ZvUPLVSXn+Ia6/Abarl3ABZp6NGTGy5PkuFRxnW12MoNXS3YqcB7B6wtOtTqT2z0BO/r3mUZ9FJ0FvBuUyGcbuqgT5Y+mxapVxBQwEAxsN3PYPNioe/wJu9L2bFU28eXECJ1IOs2VBBpUg5qwZVqcuNdcbbYy9sDUGtIV+Sccj/1J++9P+v78T/18sTX3UdrAyEjwFIJgjAqqkTfipjXFSyFca8ImkCrI0=
  template:
    metadata:
      creationTimestamp: null
      name: wireguard-config
      namespace: jellyfin
