---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard-config
  namespace: torrents
spec:
  encryptedData:
    wg0.conf: AgA1PHu9JaAb5Hj63cD+3HVzbaDfs+hBTapvYn3QsiUJDvbf+SPyjo8VYaR/pjB/qvoy3ELZnhIrZ+VMNYNlsZhlb5L+QHG8BWagZwXjxftHtp9J9Dt/Aax3ZS5pcKI6ETBQScwzYvsznkIO+hqu2iiNtaphaJm01N8qEI3bCPrMMOVwAJd3xyN1d10c59Q1sNRSYpXR37k4dSZFJfZuVx0M9A8QxyIywtFlW9J7OqMl5m0SQ5WyPzyvs5NRXoTj9z5uArRuYqQVAjTcF2aMyXRWluHHNZwXRlU5CHJXn4EZmMlZ3NuQDVzVP0MJAXV2cySPKmqtHxY87uvabxRJDBeBxMq5xBnZ0P/kp/4jaT7cDibp7QgIMZS//v/bPRV7kzaiqc5GA+zoGTUk/KSfUDs0hO7dpsvr9suUMm8WKokqy5jvgQNOn48joFAfn0gb9cxhknsLEzSJnNwj1D5QI6Mmn9/7LsErjbL99mhDTaYbivHf04bI0RbiYZjbaZcn9OF9mCH060UY05LNb+RVYSUfXhwCZiVmrMrwAcmpHevk8+h1X/k9RHAiCV3pPLAT/DKtJ7MdynFoLQtexqIhPiyvtYUadmbkL0Yg6n6AKl3yWsrXj8K6l1uiWO2636EYgScsFyvD8cteSDiT8rGwIWpmaKC8EVscIvHs9o0eQyh6OdsKL8nLsxyUa0RxhXs90WaK+YquU+LNTufZAB69Qca7dVxEbSHxrr2fod2xSZNCHGIeO8om/0psugOTbHoiFpneQXigSccZ/9F8S4u/1/ppk/ng9pe8ikY86D70OYiSbvUsPi/5YeH/1Hx6mz1HwfTaAVkHacuneNL2yu7mxJTJ2cqWqmyIlSLg5kESokQdP2iyDvfhYK851Tz5ZoQqdj/E3Ui/mbFnE1PWdrKXZ/DpBbx1RgOTTPc7zvJOmTvkKy2qy7r3KtkE18drDHkNQAyYiqQzgnnHDiqcj3nYhf4yMWdYNXMNUX4disrm6Y98pRfzm7kl9hSR8xKRWxTtdbNJ0J/O/oeZQOgWy5C0hAoz36Ce/dApvOnX1pFskz9AwWD0MVwEDxQTxkTWEKaOXWG+1RN9aBfFDlNilVS2+v3S4Cke6F00CI7VBvnhi+NeCU0LhvaDXgjM3dVIHsDDgkDAfrhNcKTjoMGS7is=
  template:
    metadata:
      creationTimestamp: null
      name: wireguard-config
      namespace: torrents
