---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard-config
  namespace: torrents
spec:
  encryptedData:
    wg0.conf: AgAjQ55jFJMhqD4oZwwR+ECV54tc23obDrGH1xoj+lCD6a9rSQrdT9ZvUnubbkEhnfZCYYDugMXZu+Eu35Wn2cjA/UMtx9h5YP1fVqh2Vc/zKK8/FOgv9JpTzeyoPkQQ+VeNkHOlwcscL4fvYC0To/n3hvgzzbWkVfycpe+FIIeBObrshgoVri5wJBFlf9x+6bJ62gTHwbRMkc+TwVAgDqdkBPlc/m07NogPn+ZbKMqns0vH5RTzQXOuch4kx/3EY4s2YqL+QKy3jJBzkkm0yGiOeD0ccn6O0Zvl8O5vO4ehPniLCFNu7COGGE8nZrS4Gmd7fLw5yiIUkbtTML+R4mP1tBKERbb8iAcG6LluCBiNOkdeAwRPqXvig3ra52L0hD6IdJEUEJnLhnm542edM+Kx170Mj9675PtQa/6zLJihwg3eZpDq8zHv/gU4Wr/iDSMrZKmJhsVkoZPUkK8ruiAPFyK0DEL3f6Zo1DhZiCB41UGsYhDjvAOG9kbaQ3KykGORC0F3v3s7gfSea+HB3uHLE65IXayX5WRe2k+cHRi6tWmTPiGC83n/riE+UHG7ycAj3DigffVgpnBQzRtWtxnFIlv7AhoDFCo5Q0aL8M3vHTD/kvbcgOhxfKOI6lvQqMhQz97XArqIY7saGwuDZgjhhRMqxJMnKFKwKgu+wnEgOOsKoqdlzBrgCntaKQokU/QjTEsPMXcKz9CTMJovBks6d/XUC4PNEtTX0coDqql8B2HNm00ad2l7zeMP0c5UeYy+xVDcvkk/KrOSwS32jo64sOgRiZ0t3M2Dp6+/KiKRRY/LH1eKJ1aAaxOQ5e/p8eEzqO2vVViVZrgrtaRU3dT82ejTiwekqbtD9BF4OFInSkWnSoeOA162Izj6OKt4Dlt2n34D5+JkBcK8kBuV9fReYkk+MEXgZVcA20Jqoh5QuMzXM2JC8yuGNjbQR4/IQd2P12mwjB2OHp9uzRZOQQTuD9KbESGRvyAbUtsjn48rWOy+rPIhDrPz3QR6lSovUq3qvFV/WkMwRvV26oO25Dm45GmcsU6VFnoKbkDQAjSZbWNU4FvRSYnsR/ix+capbAeD1RrV3i0W/YZlt3C/32Vv+/mxxdOquXkLZR3DFMYbaQ0k+tYH7MVbO+gQE1CId4zMpvn0iAULs9qXgTzaTUnQrs9XhuiRUMVKEuXSD18yRb54pZ8YF48=
  template:
    metadata:
      name: wireguard-config
      namespace: torrents
