version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    hostname: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - LOG_CONFS=false #optional
    volumes:
      - ./config/wireguard:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp
      - 8112:8112
      - 6881:6881
      # - 6881:6881/udp
      - 9091:9091
      - 51413:51413
      # - 51413:51413/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  # deluge:
  #   image: lscr.io/linuxserver/deluge:latest
  #   container_name: deluge
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #     - DELUGE_LOGLEVEL=error #optional
  #   volumes:
  #     - ./config/deluge:/config
  #     - /mnt/blackbox/media/tv:/downloads/tv
  #     - /mnt/blackbox/media/movies:/downloads/movies
  #   network_mode: service:wireguard
  #   restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TRANSMISSION_WEB_HOME= #optional
      - USER=
      - PASS= #optional
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - ./config:/config
      - /mnt/blackbox/:/downloads
    network_mode: service:wireguard
    restart: unless-stopped
