version: "3"

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERPORT=51820
      - PEERS="drew","tiff"
      - PEERDNS=1.1.1.1,1.0.0.1
      - ALLOWEDIPS=0.0.0.0/0
      - PERSISTENTKEEPALIVE_PEERS=
      - LOG_CONFS=true
    volumes:
      - ./.env/:/config/
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    # sysctls:
    #   - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    network_mode: host