---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8up
  namespace: k8up
spec:
  chart:
    spec:
      chart: k8up
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8up-io
  interval: 1h0m0s
  releaseName: k8up
