---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: ollama
spec:
  chart:
    spec:
      chart: open-webui
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: open-webui
  interval: 1m0s
  releaseName: open-webui
  values:
    ollama:
      enabled: false
    service:
      type: LoadBalancer
    ollamaUrls:
      - http://192.168.1.16:11434