apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: open-webui-route
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`chat.homelab.com`)
      kind: Rule
      services:
        - name: open-webui
          namespace: ollama
          port: 80 
  tls:
    secretName: selfsigned-tls
