apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open-webui-ingress
  namespace: ollama
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - chat.internal
      secretName: selfsigned-tls
  rules:
    - host: chat.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: open-webui
                port: 
                  number: 80