apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  chart:
    spec:
      chart: velero
      version: "6.7.0"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
  interval: 1m0s
  values:
    configuration:
      backupStorageLocation:
      - name: aws-s3
        provider: aws
        bucket: "dr.ew-homelab-backups"
        default: true
        accessMode: ReadWrite
        credential:
          name: backuplocation-credentials
          key: cloud
        config:
          region: us-east-1
      volumeSnapshotLocation:
      - name: aws-s3
        provider: aws
        bucket: "dr.ew-homelab-backups"
        default: true
        credential:
          name: backuplocation-credentials
          key: cloud
        config:
          region: us-east-1
      defaultSnapshotMoveData: true
      defaultVolumesToFsBackup: false
      features: EnableCSI
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    credentials:
      useSecret: true
      existingSecret: backuplocation-credentials
    snapshotsEnabled: true
    deployNodeAgent: true
    upgradeCRDs: true
    nodeAgent:
      podSecurityContext:
        runAsUser: 0
        runAsGroup: 0
    schedules:
      nightly:
        schedule: 0 3 * * *
        template:
          includedNamespaces:
          - '*'
          ttl: 168h0m0s
          uploaderConfig:
            parallelFilesUpload: 10
          snapshotVolumes: true
          defaultVolumesToFsBackup: false
          snapshotMoveData: true
          storageLocation: aws-s3
          volumeSnapshotLocations:
          - aws-s3
      test:
        schedule: 0 3 * * *
        template:
          includedNamespaces:
          - 'jellyfin'
          ttl: 168h0m0s
          uploaderConfig:
            parallelFilesUpload: 10
          snapshotVolumes: true
          defaultVolumesToFsBackup: false
          snapshotMoveData: true
          storageLocation: aws-s3
          volumeSnapshotLocations:
          - aws-s3     
    metrics:
      prometheusRule:
        autodetect: true
        enabled: true
        # Additional labels to add to deployed PrometheusRule
        additionalLabels: {}
        # PrometheusRule namespace. Defaults to Velero namespace.
        # namespace: ""
        # Rules to be deployed
        spec:
        - alert: VeleroBackupPartialFailures
          annotations:
            message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} partialy failed backups.
          expr: |-
            velero_backup_partial_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
          for: 15m
          labels:
            severity: warning
        - alert: VeleroBackupFailures
          annotations:
            message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} failed backups.
          expr: |-
            velero_backup_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
          for: 15m
          labels:
            severity: warning