---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: portainer
  namespace: portainer
spec:
  targetNamespace: portainer
  interval: 1m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
