---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyseerr
  namespace: jellyfin
spec:
  targetNamespace: jellyfin
  interval: 1m0s
  path: ./apps/services/jellyseerr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
