---
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/New_York
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - jellyseerr-config:/app/config
    restart: unless-stopped

volumes:
  jellyseerr-config: