---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: metallb
spec:
  targetNamespace: metallb
  interval: 1h0m0s
  path: ./projects/metallb/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system