---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: metallb
spec:
  targetNamespace: metallb
  interval: 1h0m0s
  path: ./projects/metallb/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: backend
      namespace: dev

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: metallb
spec:
  targetNamespace: metallb
  interval: 1h0m0s
  path: ./projects/metallb/config
  dependsOn:
    - name: metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system