---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hajimari
  namespace: hajimari
spec:
  interval: 1h0m0s
  path: ./projects/hajimari/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system