---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  targetNamespace: longhorn-system
  interval: 1h0m0s
  path: ./cluster/addons/longhorn/app
  dependsOn:
    - name: ingress-nginx
      namespace: ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system