apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dind
  template:
    metadata:
      labels:
        app: dind
    spec:
      containers:
      - name: dind
        image: docker:dind
        securityContext:
          privileged: true
        args:
          - "dockerd"
          - "--host=tcp://0.0.0.0:2376"
          - "--tlsverify"
          - "--tlscacert=/certs/ca.crt"
          - "--tlscert=/certs/tls.crt"
          - "--tlskey=/certs/tls.key"
        env:
        - name: DOCKER_TLS_CERTDIR
          value: "" # prevent dind from trying to auto generate its own certs
        ports:
        - containerPort: 2376
        volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
        - name: certs
          mountPath: /certs
          readOnly: true
      volumes:
      - name: docker-graph-storage
        persistentVolumeClaim:
          claimName: docker-storage
      - name: certs
        secret:
          secretName: dind-server-tls