---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: metallb
spec:
  targetNamespace: metallb
  interval: 1h0m0s
  path: ./cluster/addons/metallb/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: metallb
spec:
  targetNamespace: metallb
  dependsOn:
    - name: metallb
  interval: 1h0m0s
  path: ./cluster/addons/metallb/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
