apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tenant-certmanager-cert
  namespace: minio-tenant
spec:
  dnsNames:
    - "minio.minio-tenant"
    - "minio.minio-tenant.svc"
    - 'minio.minio-tenant.svc.cluster.local'
    - '*.minio.minio-tenant.svc.cluster.local'
    - '*.homelab-hl.minio-tenant.svc.cluster.local'
    - '*.homelab.minio.minio-tenant.svc.cluster.local'
    - 'minio-api.internal'
  secretName: tenant-certmanager-cert
  issuerRef:
    name: homelab-issuer
    kind: ClusterIssuer