apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tenant-certmanager-cert
  namespace: minio-tenant
spec:
  dnsNames:
    - "minio.minio-tenant"
    - "minio.minio-tenant.svc"
    - 'minio.minio-tenant.svc.cluster.local'
    - '*.minio.minio-tenant.svc.cluster.local'
    - '*.myminio-hl.minio-tenant.svc.cluster.local'
    - '*.myminio.minio.minio-tenant.svc.cluster.local'
  secretName: tenant-certmanager-cert
  issuerRef:
    name: minio-tenant-ca-issuer