---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-tenant
spec:
  chart:
    spec:
      chart: tenant
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: minio-operator
  interval: 1m0s
  values:
    tenant:
      name: homelab
      configuration:
        name: homelab-env
        existingSecret: true
      # configSecret:
      #   name: homelab-env-configsecret
      #   existingSecret: true
      exposeServices:
        minio: true
        console: true
      certificate:
        requestAutoCert: false
        externalCertSecret:

    ingress:
      api:
        enabled: true
        ingressClassName: ""
        labels: { }
        annotations: { }
        tls:
          - hosts:
              - minio-api.internal
            secretName: homelab-minio-api-tls
        host: minio.local
        path: /
        pathType: Prefix