---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-values
  namespace: minio-tenant
spec:
  encryptedData:
    secret-values.yaml: AgBjn4F8sDhvTtaIo4vddoQQRzZYk2ZzspXRQgvqYa2U2JgPqfJ68wiF7QW9uMRbTZrIF1cGk4rg/+cTdmLHNq7fMZ4hTVnla0j7RYJxWJgRougKOgQUmwIo3Sj/6unSnnGqQXPWdhO7pigGimXQhfS2Y3WGcRdhNpnAbZFz6G9PjxjUw8T8SMowCH3JYetkI1BuFvpzdZP02MdrnKYR1+Xhiy00FOTzyRH6+QcQndWCNtgmO6dymLljx6qhP/mCgn4rp/ObAp+6rJHheQXIyWR1turLlwTtCo3KhAcfMHX2ieHGSb64M2oJsKmhUVImyNtVLW98YSxnXdDnBXHIjyHSdQYaU8IyKqMQwYhlvgLk5o8YUsKR3wEpP2L53S4VWJmzopyFWLcmmHhBdyhcrEctjLilyLfV3UJQNFuw/Yrgz/MZ+lRaFNhdI06JBQXk/DnpYmkpmmTtoDyRH+ENq3vL66NDLfaa1tTHE/VlXYkdsv/0/LCCabFOp2lDIUfgWsqJW21lC4va4NEuWEW9HBTnQhrzbrBikptFCqzSgHcADgwShK08z4K6L69/RSPKYnZUCYVE0O8iMk2x5Em1opSQ8nduegLVys1Xkg6S7aP1lmGo8J0+UsuW4JD+GnUD20zNf1idio3CP1ek7z8wI3JJ2zCRzTLdid7i/SJYeRlUITlvdiJHGe3sB9cpj0CT19KlUUf9swXftgY4Uh8MdBu4m5ujK9fYYlmp9z+dSEdOJJQg/Jzx4FjyYCZGCkJ8bihgIJHcO2f8CZ8UMwz6/igLuwssBWb8koRFR9UTdxKdP4/nkYdYGxZc18a28HvXBdKzeqUu+iO2hAxAoi26FS/+7H0dNxUwpvOLTZXoSxMLyLPWkDw62mzFAD/v286lRkHcB7P0BvMcVtPuwpOZVpApoCkec+w=
  template:
    metadata:
      creationTimestamp: null
      name: secret-values
      namespace: minio-tenant
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homelab-env
  namespace: minio-tenant
spec:
  encryptedData:
    config.env: AgBdkJpGQnQ8PTsuBX+xEVdfqeaAhscut5rE8QGZHvDVCIuyyhLGY4P3x15ASC7nBubGouGXAL9ILLb+uqqdcqzeRBYJXoyk1LqDr7hPIseonEWH1LO1Rmq7GejFVWd7/uihwpi1ljaKZ1FCkJmZuWvVtRcypLiM2PvycLroV7seP8Fb3TKu/eLn81U9RyuA6JKxh3dHo5d/DX+Aey2sEFtl4Jb3pa+/+wZAD0xXFfjlR8bXgs/XOZIww+/FdVYhMMjZUgd7vjIC/GdZCcbnHLBEtAWvzUjo29W2pMWGJnRZ2z4AcDLAqyUyAn72jAb7ry2NPVQII1IFaml1Be5NFdxVmH3rsE/QvNGWy8SQmRQoBDKex+sKX1bji8Ls0GKN78j5iO21PoGAHC21vWE3pocTyqZJSmmpiUnFdecZAySMp/KOdUiJay9TmVqLy7b2BgZngRNwDp5WkIp3gEf2ATAuwbR7ZKPNeLR0EIN8cLtXM0kAFL/aIhSDIrrf2U5e6j1p6YaWyGstFv5iq8dsgEt+b1hvc4eTWuCKA7cf7dao7Gc0z0L0dUUOQzpqs32bg1Zqzpu+FdKs9DzMFhx4T9SFPU3fLQVn5xgzmhmO6tcYuDIv7SZ/httKK3IVWkU60ZjmUvtKgC3KjR4a82d8JzPTnabXP5HQj4spL9Q8iPoo9AnYznSC6006cDDHfv1FHOXrDTn1QIPrt+f8i+GiNsnJiMC1ClnzFoz3SgFXrmiVO3lkQH2Gm5e7dezeqnRu+hSddTgR+CfYHFzp5d86tfVSCglVUYzngdd9FNo9yG7Q+n8I0+Ny3LdgJtay
  template:
    metadata:
      creationTimestamp: null
      name: homelab-env
      namespace: minio-tenant
