---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./projects/harbor/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  # wait: true
