---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 1h0m0s
  path: ./apps/services/homepage/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
