---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-values
  namespace: default
spec:
  encryptedData:
    secret-values.yaml: AgAuI3GdfzJv4s03xx8eP/j+FRbL587xIDydKSZ74hWdKCzWv8+T6D5QVwqo1WGfkwGhQsaEeInM/agZj2CXpq01OplKE6eFuzt3kFzxETlJ90sYChJnTD1/Lt7XWTIM8p7RAc5j+tUROt5kmAGgig6z4PHL1La/HBpx9cv0XA1MOAvVbcHYiSOEEgrqQQIYrhY6kCMewPMDKZ6MAhzu0PHXsMm0gWmvpPiL0eIhe9ciKz77L/qQXoF+ik3Hr4Y6BRpTgMeYVWjvRyZLGvv0D2nyMPeKSv3p/j4nNkbDiiL0WbgOP+BW2Q05quPGzxIwdq58g8BSU0d6WVYHSpi9DV7UP/RTgcLo3uAcj4i40ZMDBYdUXWFvaZZ/PMVbHTEWDSEX+MNtr1/qJZsSxTyQ6uf9zccZWej+d18LyFKCDIv94rC1YZrvCohY4rYPNGYneY/7uCk8PQ3b/hSUm4BrlD4mN2/RqTbhSjf7b68ItxZq6ZSoELlBXLzyzVvUUT29RJQtddW5i2fenckNi0qzILMzNGyAm1sNryScZqgSrfxNuyndbsStbgCYC7lbFxo0VEi0G+XnYEp3Y0q6Dml8weGuIDILK3kXwY2U1c0jP4TXIvGGGQI4HNv1dyAEYlj0RH7U/0LX/JHvYO+cZJFLjGb5RpOtLrgr45iUNtdNk+3N2Mas0QEWsrVq4jCIZUBbJWYGxpiQCNO0SFNtNRTFAVDN6cNYBrvHS3FFicmxddVFZpQ73EobPx7BC6QHnreLw7/4nt8=
  template:
    metadata:
      creationTimestamp: null
      name: secret-values
      namespace: default
