---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-values
  namespace: plex
spec:
  encryptedData:
    secret-values.yaml: AgBp+NhLsVSe2JZjcBBMtVsYXul9+IWXkdw9Vkr/PybKwUgAUIPHxoW1+ZkvAj/osfIpHbZMZcWM0tO6LKNlSjisHLQIbrtdw8xxFgtbKkI3z/Ee/tI1wRPuls9Il93Z+zrCcCAwFoVmM5YWtnOJjQGulcVBmKn0J2kqjmcJuZznVyNRBtPQzON5iOpKUV+x1Hd3zMHtlYC/XdsVJDZhCBX8FkNMvpYzkJ10tp6MUr9SdWnWN/yqD1w2mIt/1hp8ysIYi+Axl4SbD/EnCFsHAvEWu4RDHDhFHU0jWkTiFMVi/PAzH5rgK+GJ+NJAuARs+7rT6/DRB3a4BBFk7aW7/h2ZheyKVu8/0yoX5blGzZ2naIkXYd7bliI+NXp/wDcBRGOuBaOMJtUKO1dTma27tDoqqyp/VKDR40AqFhHBnnNUQHqAXylz6lYIsAxnPdCLQGcifBMv2l1bYUv0SZzovB4mweul5YanzQiEMe/GZTWGAKcK90wwajX+VbRT8WwMxSHdGP71tRG1a2nIcGQVzz3YbONBjXlyq5d1Q5+Hx/89YjpMkigYwnJ7mEvyn/9LPi1A77svaAWiX5iYYeyzUpLPu5dAmQIn1D6aHwtl7RvtavH366v5G/PqQ8bPdxvBf3U9x9xcyGR24CcRVdpQxoL5lAiUz7QhSOzZtvjjioEj1OpSbCwJa9LQkz5+cl/xrT1ZkIeb07HxtilkHSKNSmmEYTOIj2RB+uj5lpfaWHprn4dG1LFI49+356SDO5DjtB6pLxM=
  template:
    metadata:
      creationTimestamp: null
      name: secret-values
      namespace: plex
