---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-values
  namespace: plex
spec:
  encryptedData:
    secret-values.yaml: AgCmthH+qsX4Pir0pw8WhNn0KBDyGBJt+ozcrg6KIl606ViDpsYfT9uH7KKcBqK34AW338NdjVMPd3q3x4Yy9UU3vOVr/O/70c8CyeXNZah8Bx1HxhvJli86kzVsmTT2Mn07ESWh6jH510qmy25qyyIX7Ks6e1exh94sNQ3IVYR1+ZIF5wyTrQLDg/gygxhMjPOi8Bg5iVMrpcVPs9MG+0ziTaPUoUxbfu/VSeuB/J2TzcPRYiP92Ew/eVUzh1QuhdLWObbLT2TdEe/O7pbgqGX+FopseLzoSg0pivczuZ0jp442+36JyxXsfUpKx7lcndFSd6cwxRD/pGqPQtXQdAPii828DpLDbdjBTPbNIbq99YlZ3oknaKQYBh0Ohz2uyLBkBkUstVGHV+3Mfa8oxYnPh9z51s1UKvl8sOWiKqHkW6u7llC1vXTZhkfN6eKhMISklcBUP57mCUTTs6NWkoeu4hRtD0QpkuyX1G1TcQ3lom2s6yJKnU80nSPWY1eWOppGxz621TkEI8DbEdBIRvHqO99kmoJPPVawoY1ckwSYN5NKcmYSfphkn5S938KR5uUF606doSu/wlEJ7GRjpmaKzhmifGjuWQzWIG/WMETg8YhuPR1rHIyYyZxw32NhRJ1z/Yl+msncYlpesUKmNweZZYGb6NnYpPZ+qLUMJPz/pERHd5ZBWY7g0rPtAa7LIMrnCUCqRHG8Xss/7H6tRUv4VVpM4A6t5xwyCyO2AVxrF7wknkYSvN8RnkjjkVqDBsQ1mmQ=
  template:
    metadata:
      creationTimestamp: null
      name: secret-values
      namespace: plex
