apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  path: ./cluster/addons/velero/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  # validation: client