apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: devbox
  namespace: devbox
spec:
  targetNamespace: devbox
  interval: 1h
  path: ./projects/devbox/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
