---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hound-server-secret
  namespace: hound
spec:
  encryptedData:
    hound_secret: AgAc/KH5btyaBiz3S2z5cfWM9JRxtd0tGKuHzUwDETDfcuPAaFUJetqxhGhd160evUZymTvuSDm0JKSoaT+ebBDD/XcLIpVHLrZ1UjQovprM0v7N65fGW4CMoWULMriRRpw61DNP/Ta9NiqpoPtCuFrc8PReR9IPrfyzoHEAHz9yVOslCp6a1JYgY+z0wyP+AitLh6ZjCSa9NMpIXHZdnnZ0TLucwDvga37pyp+ZazEMq+DuEqSC05dJbOqMFmBDT3zuu8zgMAsXsJEg+ZbpCEXqF/8H0UD1pFQpq1wZfMnf7RQWMV0BNiFP6fHKLy9jXGgM5dWHqins4tizZMiMXk6IJUh/NGrjWLx1O3PyJvRF0oC227vdVju3fB5inzG/AxZorkN+NLIqR2fz8LozkeSMQm7FTpFd+rcLwe16BqJUcCtu5/pCOA5qj0NoOU+o64GO1fnF4Cr8ftd3vbXGtZODmibsaUo83ViuetObMsW+RmjhEKQkI9RzmXhrMsdM190O+HAqkvz72TYrHECRhyJXDDz0MmvmDsZbKOgNDGXmKHm/sF8JXNyTGjnBt2qXfeE4j/DnsfCWnCmpcUzOC2/Mwi9z1xabpwregTnuiqrBub7YWu1a/5TacYe0K1uXf7R8pKjjwaY3AWYlIbUSUYTvHkOj4iqeknwhPs6C+DzxKX494NKjgUksPkCKSOot2BWJBDw/O0wLo/G0X86VieQcQxVZ0IBrDjHwACD52+yq28sXl6GLooXSDd6s
    postgres_password: AgB4t5r/HH65if0zwmazwcL41BhfWPc+J1hd2ec4s9BtNW7bJj0jdzdcqdEpai9Di05+oif9i1ThJYETR6pEhG5Y6Oh22hmgoF+WHn2PFODdR/87hI1a5ychxoWzxxOg6SX729HthlJR3ee5AnFLgzKDmuo8QRNnB8/U3jakuFKvhsZ7I+3ji8pcXaI1kOlP+QHGQak8dxVnlVTeOQl3p+rVzFYhshMxOoTyqzkmgwEZebgNA2icR4+tGjX31GWJhBe4H5S0K2bB0RFhzI5pK0t6Acb5JFvz6CDeSd6msDTSYvEwyM3Hhn/0TIqwXfzy1JA8JujLtHOW7c3Ad+pVlGtcsTxtJEZCivwStqEi90hFmlpKp8hS1TxrsBC7ibZrnJm4QuEAfVsqXjFEgRrgqO9QHESJw9TMk3JBmEUxYNXjYlczWNlN0PtDy/uyR985ERlCOQfDPS5u0GTF3VURuU4aGl93t4xBG+SToRjC8uDRM/c3n+PgBa1hbvcbcX+1byBMvuCJ/m+dr/MQ6tI6kMU2UDh+wRHLbu7tZX8Up9rOW++V/PWxUINIWSuGrf3myuIWOVqo14CssDKYftLoi4EgNxvlKVlPX2nGxNXKV7jJR1I2qQLOyX0YQf5ztgdg1PQwAS/Mmyg3qJZsFZXR7rkyF6MdCpDqqIhK0VReS/tY752CbW7VhoBWLTwf+W9Ms2ou4eRHdSfFsghMLeSbvbLv+CNcP8j6Bu+x3PtiK8Lyig5evKAxfw/nNm8W
  template:
    metadata:
      name: hound-server-secret
      namespace: hound
