---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hound-server-secret
  namespace: hound
spec:
  encryptedData:
    hound_secret: AgDDuHFDYZJkH8VMNIxwqBHPyXR8MFz0+LpcQhO8hgciHot4/rDAjVRBVWLDORihJadioaCZ+DuiXGDC7Lflbx5mpGzdA9VK2tKx+1d4+cRWiwSY/0ot+tuE2bisc4pRseIEIT7QjovbTnkDsM+iNleTqSYUiOGv16zPfBLlaq2JXFlwvkMcLG40th/qd6nFngtpJNgicPx4xbwlt7evHYE48BcZe6JwS2r8N03aJ+x6QaEX0+SeA7ZYRJwckUV8KPhnoWxM1DUYDwOHo5ulh3MbMwrxIrYtOHiTEZIHagRflOWB5FdcmwEkxsSYPoXuA+SNLVTbNzzk0CzDhxFCregtA8Mtfeoh96KmUdh54bVcLkN1eipLgWeKZck167Zj0F899SsezPu9X1G6EPtAEoPwCT9v/baQJslo246ppWj8Adok8pR2G54gjUDvHAB1srCxdeeg/athuyVDrHUf1Kdstec5JghoOrs49YH34cdaxkUOYtlXZqJWFTbLCaL1wrfPhtdtbhZ0SYsBIpQB1OHI7IpCq7awpSAalsXCYu3ugz/Ldv3BSc9lTlFN64qhSdFsh3XeTptOwia4N/coBcaT7nqPacVLSB1VEx5CIegdzGt7Sqt6lNqYUukz98bWBSsoS49WJ5WSlT2UDdCEBilHXlET75GFsDRqbhorvQfwiDbkaNnZ1ZEkAByYzhfwPqEigAo6OUV4zddmmdO141PNF76BxMEIoTURicKKGmkIXij6RigkQRNu0cOwvg==
    postgres_password: AgDT60vXDE0yPfTaxihkqpePIE4FcyglLrbOiZJnCXd7q50d8QgxshS++aOZef2VRou2RfQGtqIXQS7ceimg8Y1lBvP9wT57nZoL5jIvF+PwhP1D8CYSQw09WDHgvrDb1/iAydTvOlYsJBVmGr0AOOpLHeUsnT1Wavnxjh+8MyKZrBG1VJKLGmlG/ap5RKck4IoIhqJcPiKETrg5NssX/kFB6IiRnKD+bRkIX2H99v9DfCI41jfHedjWJvaGreLK8uk9R6gdYZlZ29n+4AXd+lJt64bC8D/gscWdRoidZkSmqHN6Y8pjDYhB9ypdvPn8XVr+hRmB6ZkX2V97548hAqbkcri/GaXVsjuy78z6efSJOJs0/87rpO1xrVZ9s/V0yvYdEvYKBlkbQ6GfS+MVyE9rlAuErqOpjEm+L/IVOG10OCi0EjmCXeFVJN8CMGNrroL7kCWJC1Lca9zunpp49Fo7XDdFH4VGDIo6E5KKO3NPLFCsmn3grtL2strTwUKV2rTDW5we/ZXs7cnv3MAUkJIlrEeeSKw+vRVb6re8nTIf/KR0QfhNmBGLxOQAdivtUjoYUVnShi3UXqAWJowVSiMj5/cKblrLNh8fwKQM8fWnq8rKf8bTj0rQ/fgHrQVFiBoxA+CyNtBvYRjgtRi5mGibL0ftizBNR+5GUyu3NrcF1SVJ8oYjf95KhLyGow1n7PpkSbh77d+VBdGukAy0ZXv1+EOcB6jtLbb8lfAcxDoKKOvbfHt738GsbfG/nw==
  template:
    metadata:
      name: hound-server-secret
      namespace: hound
