---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 1h0m0s
  path: ./projects/traefik/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
