# # hostpath
# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: blackbox-hostpath-sc
# provisioner: microk8s.io/hostpath
# reclaimPolicy: Delete
# parameters:
#   pvDir: /mnt/blackbox/media
# volumeBindingMode: WaitForFirstConsumer
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: test-pvc
# spec:
#   accessModes: [ReadWriteOnce]
#   resources: { requests: { storage: 800 Gi } }
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: blackbox-pv
# spec:
#   capacity:
#     storage: 10Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: /mnt/blackbox
#     type: Directory
# ---
# nfs
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.214
  share: /mnt/blackbox
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blackbox-nfs-pvc
  namespace: plex
spec:
  accessModes: [ReadWriteOnce]
  resources: 
    requests: 
      storage: 800Gi
  storageClassName: nfs-csi