---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    # runtime: nvidia
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
      # - NVIDIA_VISIBLE_DEVICES=all 
    volumes:
      - /mnt/irene/plex/config:/config
    #   - /mnt/irene/plex/tv:/tv
    #   - /mnt/irene/plex/movies:/movies
    restart: unless-stopped
    # networks:
    #  - cloudflared
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
