---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: opensearch-auth
  namespace: opensearch
spec:
  encryptedData:
    secret-values.yaml: AgCQwLob6ieRjK2eoakyyW86QkCwibgUubCTXyCgFsmfdndShzWfBz9XB27QkyZCw5feoJlwQOFghpV1UNSYePH9J1hI5Eon65zx/A+ZDyrb6CSbPn0j5zs+a9rN8NB0j4k1ZG8YrEaP+r5uCZV3PDiCRgv5iSSPpidfMwEhAzVnnBIjjgvJAxNNNkmp8E45x4SXTMj5KoKnrf3iJnNARqCz1mS3CQUlXAQNwCYq8T32i4FRkBmKPiEc3w3s3NVwMYssXwZyUtLmCjMoJ0kgwp5/p6CaEwkg+WIZWdg/OtR8borsyIRvaQHwsnIMkHYUf+W1qr8olR+QYicSrfzIvIJH7SwQzAW+8KyaoB9pKrHViKLC9mur563l0r2G6H1rbcdc1vk9xzWvzDcvhO80pFTvjMOkSn+j6Zg3jkRppjtYY5mPIX6aAeeTZgvPQHSZXYpWWP2ER4FZaF/yVDqo48KjpXtV7bcA9nNweLu3HK73Gwu8rYZBywDEqkBxyIWyN4ZOMKb47IM6DlNbQGjTrN97WjdTbTDjaGlV965Ah9xn0Eja+JXEhE9NFfI+YMu14ZNjJQT5weoP0gs6QXb5QrBJLl7gbwAlM9drhl1rwg50Fp2gWXRcpHrAKkSQV39idcj9JTSEdOxkWHaAOOTPrj560Kq7Sd7ZrlUGj+avUa1KQI4WRZ2F0L9i/syEwVom3bRWyNWmf4VpfVk3fsum0fe7m5utewnPOHfCuh+P/w9xiUXbKHWWmg6e6iRj//BR2S69kDZnb2ig3r46TQ==
  template:
    metadata:
      name: opensearch-auth
      namespace: opensearch
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: opensearch-auth
  namespace: opensearch
spec:
  encryptedData:
    data: AgANLiVfDRWOpJHJgDAnbTWEPEocHODWrcbaQc7QHix6VwkHLrSFZkGoTfWDjEGm9GPWte33eUxZ9JJNFURFQ53XD/mEJko4vpCTDXSmxdd0BlXwBTnNI4UDAkRhOPlMH/DpThTsbtCvfIZ5PEDU8nhc8KmIdKvziYeMSsit/ZU2EVgdRa/Uv1VC1+RDXXLw7Xmo9/VHXfVCHYkgfrJnaOV1cAlnjXgHNCr/eFPc9VQZMyDZolpuVyEEMwT7HCCPok3s9gXLMYp/b0uxOGFH6Ddj+W4x35KY6UV8lizCikN7kaw/su48L8DYfdom0BP96rTuzkZo1hXnm0YO3VCyVXGsJ7cBI6sS8IdGYfavEEmqd/60WMaXsHkjrp5RKxCM696OprHCO89/NUbxNQSFXRHioeI75EBVPYQ5yh2XkrGx9zBG+D9lG/UUwFg/jeA9dJVZerDDldKhRTlPPgVpnrKGVrqC2HKXRqM4PDlTkgB+zf2XLER95kOTkjOKCpM3k+TriXnBtjqn9vZ/Crf2r0FpYr4pdYt2JmaccnKaWNftsWdD4yrNyYExV7fKsiwi6tJfFQUSyt3CLQeoz07cII93My+wdtHTKy2P+lilorJUMzLkxff777c5Dz9UjndIigheBbcIY5GR3YZsJn+qRp0lYJDZMST3HQHWD6I+9P+JSP7bYaEbrQGv39ZPaRcl8WM9wS7XYjR3zXqiVjVVrahLR6o8hdvrZCabhqBWKtuMsRndliD1MlFtygOGNXmHzgsY61i7BP2ReFFiOQ==
  template:
    metadata:
      name: opensearch-auth
      namespace: opensearch
