---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: opensearch-auth
  namespace: opensearch
spec:
  encryptedData:
    password: AgB3xZzZgB6+K6mg5GoVKy+6E5ZDlPSyXFwl37pJL0f1pEWpf/SDzZ1csBFOiitFkifvi03Cri7vw675o3rilgcjsBTyEiiE+u65K0HR78N9zrbaVMiBi4QHKp9YXMFcAzOex2VyEdudmjirvZZkShpWHL+IiL/v5D8xVHhOUWDUxY881d1xBxuMSSO3VBUszeT8EoAK8ztpgPWLqFp3dEOn7saWbCCh8fk2J8Y0G4cgGAM+uk+nLVMtM06xHh8U/jMEy6a9hb1Sa5b9LflMNDUN2DZa4BplU1Wklk66+U/c0twIBbKfwlkS6JIa4OEbJjndXMw960QrAdZwpTTOibYtIbLH3uyo724JiNBtq+WAsOkMuI0S9jWz63YG/jVwSzi68TD0qRVJe9B0Frw30bhkfE9ZrKzyOjl2cOXHPNXuVNqsPmtzlGwX2XtYvlwwghKxbwR9zZX5NGOuWftCqOOMyOm8lh0MZr36u77mUrb2uyvStEhHUCTywRGGadIs3Io23j/KvuFWD0493G1EFG9sEWUgEyn200j40+cAOgaxnY4h4yql4C58OlvGvC2J6P0+GCuup6eOMjnKr9jk2cvoEWtSbhUpy20PeSVGNYniF1adiB01hjk/GSDBUKy+xtTflxTBoflKB42+3aw83KkcJnDeqExtDd+D1ZbPowIUG/Jn6JmsZ7wcpFE+JHRiFGvonY1K9X2JHuST1WMU6tPqflNdZ9SSqqdKVFdZ
    username: AgDYYjxtEhWr6FjCX3PoNx/7mQ7LDU/STzT7lt6dmN8DL3ByzlcDptvIS/9nrB6KxLRSAH+9OLZ153cuVWRGkzXV0I0smNx62mj+brC3juOGXosioI+K2ZXY3wtF8KEothxMYP+QD86/5Ent/kd3QPGgwbMulzF5epEfEgFcW8721ICAdb3K5Mulo3uzLStcBJYFwFeAzQVBexr+ah79oIdztOBmf/22ao1Dh1HtLCoM3/tW8gxjXWbGm8RaHaRfVp32LyDoVKPxMcUv19tvWG7bQ8BPozZwzeZRP78++5NVQxLqGVFBoWkKvtELU8+R44xxKZRSSfp/cFSDzPdvy6Y764LexFXqF4tocTmn8WgZXTYxqab6kFgy/II+9wdZH9/UfwIzScuTaXm99CrHgFHN1H96QqXaE7h8Z+4NUV2Jqt9CgnXJU3Lpfy5tt3pafeuGaqekEI2kwE+MY8JWzJuzLW03hAB4BgKjpj66BiGHTvi8b7KbSE95i30WargtphmpKFZGPYhHRgshhSpfar+yCIJw5WcPMcs5Oqx5FRdUoXrT9SkmH71fxz7BUFT1C/R9A07L1rMA7dUPlZyOOi4TxfF087Q3u6AuUN2xXEZAB9neK2BiJpuT4luUCZw93sdOjOKbYvQlFxqBx2hUYYjD6i3usX0+JnlPn2u8j7x0sGfegG5D+HabLpZlfggh4Wk+SsJ/qQ==
  template:
    metadata:
      name: opensearch-auth
      namespace: opensearch
