---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflare
spec:
  chart:
    spec:
      chart: cloudflare-tunnel-remote
      sourceRef:
        kind: HelmRepository
        name: cloudflare
  interval: 1h0m0s
  targetNamespace: cloudflare
  valuesFrom:
    - kind: Secret
      name: secret-values
      valuesKey: secret-values.yaml
