---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-values
  namespace: cloudflare
spec:
  encryptedData:
    secret-values.yaml: AgAISvlymyPQQhNu+mTSPIUs6W12SC7oLMAy5+97lAXXKOahYBy1IR7Mc9ACcJpT/bvYeCJ2N+XxgDApDbgTAeZ4TiaD9+e9L54GQJ9Hs9IQ5d15MOinKPbxbVI8NruGWOQbOPCbZkI1CX+kShU71ldkmKedQQLUsUuUjKjd/YhXqvlaXlTV1Afb8G1d219furo1d6ne35lBUPW3usacKQb3HxNj8vYI61pMisLg5wxUiImnrzSWjp2p0nfM0LA636o2ZcrTopxq3NSvhdGsVoW2nSLRnjO5Nkzo2y7s9sEvDbed/Gq/6cETNMM4OggTwkP4sm3tHceysvKh8gAF2lInYpULKUg7DstrfL5l0pR0eVj+2kxPSYl+QIZmFJVjl4NEzJ2ncBO4Tw2T4sZMlSfaC+g8wKx2FQIWmgZ5cDX3CXJp+iTlY+hT1eqF/gJgWtaCDtrQGvH/RBFYC6Hf57eVFj5BLv8TShvMQPqDt9ANMBHEVKat82FRFRpFlaTmimTxaVJQilgMYs4zARi6TlOcqZc5utaHC1jSRUG+pdkswDoN+c9TpVEjA/I1koeKiJR6ka4i4fj7XEncGfEHC7hR6A1+MR5caBKKTzS26JFAIpnEMLAP12NmeqDvBAawAC0K6Ctff5u0UL542j2Yjigzhl4v+wh02daQqvo47IPZweTb5MGA87ra+JW9QB0xf62Qo/CdpMsJfKOy0HJv/yTxsPNUrvZHBKVD7Ssz3ruhBuXNIu3uoFvqDQgxuSlYEcR2JmNrYtNg4zk77GOyI3gq+gXkjU3IZyZrRrB3g1zXMEdPyf1E+RIonDmu+/Z+VLSX3ONJSr80zwyXseiCM6VOS2Oiq1WkBSlLof+dn5rssRhrZlwWHIYBvlJeS4IgxfQ5Zs2Nc7Cb4KPbUJzcRQl9noMPvAIdLjP6cIdTKTa+GcAHsJ+AYnki6ZgIi9TKg96D0ScTi5KQw6dmLGuez1BAGr4p678=
  template:
    metadata:
      creationTimestamp: null
      name: secret-values
      namespace: cloudflare
