---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-values
  namespace: cloudflare
spec:
  encryptedData:
    secret-values.yaml: AgDfGoE/gw4xAvaBiyoMhYAFRaOdt3zCUXGHda0JAFMXZl5nEfVIUoTu47WVW1rf2x0lLy5Hf5kHFJ9iqrQ+0eqGc8P/rvsvshuwiKFbZiKvJlNe8Jys5p1j0WcDl+K9fZliz1kN4/6uQXyCsQKp3Z28MVmbEGJqgy8PGa+HKuCZP3IpJOrxQIEmZhjveH0azkvdeA/fbIxf4UnoUqClE0YPpXGOuIXW64/QPOfy36PVkQkr3tCC9uI4uRWE8tjwensF/0MJiB4mz33KJ/0ATUe9d2NPslj+FrhUqXSx+3WWlgXuRRJHcdxs3O5lZJAxODKh3YRusIjUF/Sk8nl9mY3IEJNJ+2S5WkcWxjpMDLBSW4I5l9vethZaQfXNNkm39wlH7riEYvxtG7unAeZ6clFYGCriX1GFVytPcSqElXxi8BnFlWCeNO1Dt4TUh9zU3ypdnYjPEI1rXOW/udaGLhaBnXEvAP8LKB0ywOIAS467sUrajA+ExtokmMkDwfmw5nBhj5uDbG2e84Zu8JlxjYWarQNDMsqWO/Lp+WG4bjiJzH2v7B1qqiATwwL8VEHlfU4VYBStD4dinfIwruxWo1A0kh47nHnGCe8AnrFcJguAe4CngBdpPd1eiEkJ1VVAtnJ4PDXre2ZZrGD+Fm5oqe3XalBhpDNQAVJspQkVNqnSpPZ5L4M0fuEOeiumlFebwUMyECrfm6YHf3cgtTuBPrDoL2UrX+GwhVarW3Ixsx3GZUSaCSf11KZDmhWggJ/blMVYbiuuh05opaguhFhMJFq/CRFg0IAIS2knsVFtXZroqz9Ho1GxcBPKqooQcWgP9z9Xc1CIO3SO1Tfr/Q4jzpRq4wx7tiZrvTx2VYMV8zte7/u0W6qAuJ2PJIIL5seHyHedoj4CaqAiBdPN0ZeZhoNG2xgzekH4ox9SczUenVVXUChmB9ASg52CyAKy5wff5x1pZYk0A2e7v4ph7bq5AED4DIYwqO4=
  template:
    metadata:
      creationTimestamp: null
      name: secret-values
      namespace: cloudflare
