apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubevirt
resources:
  # App
  - namespace.yaml
  - kubevirt.yaml
  - cdi.yaml
  - storageclass.yaml
  # VMs
  # - openclaw.yaml
  - sandbox.yaml