---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: openclaw-vm
spec:
  runStrategy: Manual
  template:
    metadata:
      labels:
        kubevirt.io/vm: openclaw-vm
      # annotations:
      #   kubevirt.io/allow-pod-bridge-network-live-migration: "true" # requires bridge networking to be enabled

    spec:
      evictionStrategy: None # set to LiveMigrate when bridge enabled
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 4G
        devices:
          disks:
            - name: openclaw-vm-pvc
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: podnet
            masquerade: {}
      networks:
        - name: podnet
          pod: {}
      volumes:
        - name: openclaw-vm-pvc
          persistentVolumeClaim:
            claimName: openclaw-vm-pvc
        - name: cloudinitdisk
          cloudInitNoCloud:
            networkData: |
              network:
                version: 1
                config:
                  - type: physical
                    name: enp10s0
                    subnets:
                      - type: dhcp
            userData: |-
              #cloud-config
              users:
                - name: doctor_ew
                  ssh_authorized_keys:
                    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDJZxx2Ovjufzw5VeGtEuZMlnrZAmqE6Y7khqsBJffZHkKJTlLRTtviurRRZiVNwZDrWK5fKKZCrUuDAl4pHM/RHo4QKHi9JEI/PAKuNiPSO/vbrtk4Ab6CAV8M/R+ZYrh4mXlA9MLb9T2l/17DQ7VlFH2yAWZggKr1ud3plc265lyALxQuukyhkMnNSXNF3a0rE0e9FIhe5G0qrnP18kpocNGf/lW0b3O67yOZwG5FGUndyWsLHFDe7M9YauZo0zwdZhGOubWWQgt+BByVdizW9ZETzwpjXQcoiyqkS9ov3pj7buQ14hRd32CHQny3LsSRHQTeUJ5F/VfMxEf09i1LYK31tP5GjOEzjMGfBtXE0NRHEgkW3FKSF5hsqevgm8DzvOi8+GnyO2YDX7t8MK6uoVmQI7+FoU+dK0ZDgE0BLCckcOfXUfSKBuRDGwRWjpJJWG5VW4sf2tMPV5Ps17poHz9P7J7YTzFDPWdOZQgj6Yb7fk4dWT0sJPzJfDsPLGr7e9IBeJ9oSFBUdoELePMKIsS/GvWoSwO2f7FOGruPjVHpRBf14YfAqGpf64sYZ0W7u6Kc4vy9Cc7ROg3L3+fLVaHfGrYRtUB4H6UF+wC1cFh3IO2bsT2MSKkL9Wv5DausjPNuCtt9nHo8zKxVvp0sCai1MA1HZWOlRWa8dzPWZw==
                  sudo: ['ALL=(ALL) NOPASSWD:ALL']
                  groups: sudo
                  shell: /bin/bash
              # runcmd:
              #   - "sudo touch /root/installed"
              #   - "sudo dnf update"
              #   - "sudo dnf install httpd fastfetch -y"
              #   - "sudo systemctl daemon-reload"
              #   - "sudo systemctl enable httpd"
              #   - "sudo systemctl start --no-block httpd"

  dataVolumeTemplates:
  - metadata:
      name: openclaw-vm-pvc
    spec:
      storage:
        resources:
          requests:
            storage: 50Gi
        accessModes:
          - ReadWriteMany
        storageClassName: blueberry-nfs-kubevirt
      source:
        http:
          url: https://mirror.pnl.gov/releases/noble/ubuntu-24.04.4-desktop-amd64.iso
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubevirt.io/vm: openclaw-vm
  name: openclaw-vm-svc
spec:
  ipFamilyPolicy: PreferDualStack
  externalTrafficPolicy: Local
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: openclaw-ui-http
    port: 18789
    protocol: TCP
    targetPort: 18789
  selector:
    kubevirt.io/vm: openclaw-vm
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openclaw-vm
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Autonomous AI Agent
    gethomepage.dev/group: Productivity
    gethomepage.dev/icon: openclaw.png
    gethomepage.dev/name: OpenClaw
    cert-manager.io/cluster-issuer: homelab-issuer
spec:
  rules:
    - host: openclaw.internal
      http:
        paths:
          - backend:
              service:
                name: openclaw-vm-svc
                port:
                  number: 18789
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - openclaw.internal
      secretName: homelab-tls