apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: openclaw
spec:
  runStrategy: Manual
  template:
    metadata:
      labels:
        kubevirt.io/vm: openclaw
    spec:
      domain:
        cpu:
          cores: 4
        memory:
          guest: 4Gi
        devices:
          disks:
            - name: rootdisk
              disk: { bus: scsi } # allows TRIM
            - name: cloudinit
              disk: { bus: virtio }
          interfaces:
            - name: default
              masquerade: {} # NAT networking
        features:
          smm:
            enabled: true # Recommended for EFI
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: openclaw-rootdisk
        - name: cloudinit
          cloudInitNoCloud:
            secretRef:
              name: openclaw-cloudinit
  dataVolumeTemplates:
    - metadata:
        name: openclaw-rootdisk
      spec:
        storage:
          resources:
            requests:
              storage: 100Gi
          storageClassName: blueberry-nfs-kubevirt
        source:
          http:
            url: https://cloud.debian.org/images/cloud/sid/daily/latest/debian-sid-generic-amd64-daily.qcow2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubevirt.io/vm: openclaw
  name: openclaw-svc
spec:
  externalTrafficPolicy: Local
  ports:
  - name: ssh
    port: 22
    protocol: TCP
  - name: vnc
    port: 5901
    protocol: TCP
  - name: openclaw-ui-http
    port: 18789
    protocol: TCP
  selector:
    kubevirt.io/vm: openclaw
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openclaw
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Autonomous AI Agent
    gethomepage.dev/group: Productivity
    gethomepage.dev/icon: openclaw.png
    gethomepage.dev/name: OpenClaw
    cert-manager.io/cluster-issuer: homelab-issuer
spec:
  rules:
    - host: openclaw.internal
      http:
        paths:
          - backend:
              service:
                name: openclaw-svc
                port:
                  number: 18789
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - openclaw.internal
      secretName: homelab-tls
---
apiVersion: v1
kind: Secret
metadata:
  name: openclaw-cloudinit
  namespace: kubevirt
type: Opaque
stringData:
  networkdata: |-
    version: 2
    ethernets:
      eth0:
        match:
          name: "en*"
        dhcp4: true
        mtu: 1450
        nameservers:
          addresses: [ "1.1.1.1", "8.8.8.8" ]
  userdata: |-
    #cloud-config
    ssh_pwauth: true
    write_files:
      - path: /etc/ssh/sshd_config
        append: true
        content: |
          PermitRootLogin no
          PubkeyAuthentication yes
          PasswordAuthentication yes
      # Enable automatic restarts for services after they've been upgraded
      - path: /etc/needrestart/needrestart.conf
        append: true
        content: |
          $nrconf{restart} = 'a';
    packages:
      - qemu-guest-agent
      - docker.io
      - docker-compose
      - curl
      - git
      - tmux
      - vim
      - xfce4
      - xfce4-goodies
      - tigervnc-standalone-server
    users:
      - name: doctor_ew
        lock_passwd: false
        groups: [sudo, docker, wheel]
        passwd: $6$Y76t8nz2SnXzS3Eg$rPUYrqu2qQOgiO5Qo5HjqiDMQPgxISrXWIMj8tjatweqmK0eYGlZuT8ieayQBVM1hbs5Slsu.K.ESfBzHqE54.
        shell: /bin/bash
        sudo: ALL=(ALL) NOPASSWD:ALL
        ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDJZxx2Ovjufzw5VeGtEuZMlnrZAmqE6Y7khqsBJffZHkKJTlLRTtviurRRZiVNwZDrWK5fKKZCrUuDAl4pHM/RHo4QKHi9JEI/PAKuNiPSO/vbrtk4Ab6CAV8M/R+ZYrh4mXlA9MLb9T2l/17DQ7VlFH2yAWZggKr1ud3plc265lyALxQuukyhkMnNSXNF3a0rE0e9FIhe5G0qrnP18kpocNGf/lW0b3O67yOZwG5FGUndyWsLHFDe7M9YauZo0zwdZhGOubWWQgt+BByVdizW9ZETzwpjXQcoiyqkS9ov3pj7buQ14hRd32CHQny3LsSRHQTeUJ5F/VfMxEf09i1LYK31tP5GjOEzjMGfBtXE0NRHEgkW3FKSF5hsqevgm8DzvOi8+GnyO2YDX7t8MK6uoVmQI7+FoU+dK0ZDgE0BLCckcOfXUfSKBuRDGwRWjpJJWG5VW4sf2tMPV5Ps17poHz9P7J7YTzFDPWdOZQgj6Yb7fk4dWT0sJPzJfDsPLGr7e9IBeJ9oSFBUdoELePMKIsS/GvWoSwO2f7FOGruPjVHpRBf14YfAqGpf64sYZ0W7u6Kc4vy9Cc7ROg3L3+fLVaHfGrYRtUB4H6UF+wC1cFh3IO2bsT2MSKkL9Wv5DausjPNuCtt9nHo8zKxVvp0sCai1MA1HZWOlRWa8dzPWZw==
    runcmd:
      - systemctl enable --now qemu-guest-agent
      - systemctl enable --now docker
      - systemctl enable --now fstrim.timer
      # Install Brave browser
      - curl -fsS https://dl.brave.com/install.sh | sh
      # Setup VNC password for doctor_ew
      - mkdir -p /home/doctor_ew/.vnc
      - echo "$(openssl rand -base64 20)" | tee -a /home/doctor_ew/.vnc/passwd_clear -f > /home/doctor_ew/.vnc/passwd
      - chown doctor_ew:doctor_ew -R /home/doctor_ew/.vnc
      - chmod 600 /home/doctor_ew/.vnc/passwd
    bootcmd:
      - vncserver :1 -localhost no -geometry 2880x1800 -depth 24
