apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: sandbox
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: sandbox
    spec:
      domain:
        memory:
          guest: 4Gi
        devices:
          # maybe remove, trying to fix no mouse when using vnc over virtctl
          inputs:
            - name: tablet
              type: tablet
              bus: usb
          disks:
            - name: rootdisk
              disk: { bus: scsi } # allows TRIM
            - name: cloudinit
              disk: { bus: virtio }
          interfaces:
            - name: default
              masquerade: {} # NAT networking
        features:
          smm:
            enabled: true # Recommended for EFI
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: sandbox-rootdisk
        - name: cloudinit
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              ssh_pwauth: true
              network:
                version: 2
                ethernets:
                  enp10s0:
                    dhcp4: true
                    mtu: 1450
              write_files:
                - path: /etc/ssh/sshd_config
                  content: |
                    PermitRootLogin no
                    PubkeyAuthentication yes
                    PasswordAuthentication yes
                # Skip 2 minute timeout waiting for all interfaces to be up when booting
                - path: /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf
                  content: |
                    [Service]
                    ExecStart=
                    ExecStart=/lib/systemd/systemd-networkd-wait-online --interface=enp10s0 --any
              packages:
                - qemu-guest-agent
                - docker.io
                - docker-compose
                - curl
                - git
                - tmux
                - vim
                - xfce4
                - lightdm
              users:
                - name: doctor_ew
                  lock_passwd: false
                  groups: [sudo, docker, wheel]
                  passwd: $6$Y76t8nz2SnXzS3Eg$rPUYrqu2qQOgiO5Qo5HjqiDMQPgxISrXWIMj8tjatweqmK0eYGlZuT8ieayQBVM1hbs5Slsu.K.ESfBzHqE54.
                  shell: /bin/bash
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  ssh_authorized_keys:
                    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDJZxx2Ovjufzw5VeGtEuZMlnrZAmqE6Y7khqsBJffZHkKJTlLRTtviurRRZiVNwZDrWK5fKKZCrUuDAl4pHM/RHo4QKHi9JEI/PAKuNiPSO/vbrtk4Ab6CAV8M/R+ZYrh4mXlA9MLb9T2l/17DQ7VlFH2yAWZggKr1ud3plc265lyALxQuukyhkMnNSXNF3a0rE0e9FIhe5G0qrnP18kpocNGf/lW0b3O67yOZwG5FGUndyWsLHFDe7M9YauZo0zwdZhGOubWWQgt+BByVdizW9ZETzwpjXQcoiyqkS9ov3pj7buQ14hRd32CHQny3LsSRHQTeUJ5F/VfMxEf09i1LYK31tP5GjOEzjMGfBtXE0NRHEgkW3FKSF5hsqevgm8DzvOi8+GnyO2YDX7t8MK6uoVmQI7+FoU+dK0ZDgE0BLCckcOfXUfSKBuRDGwRWjpJJWG5VW4sf2tMPV5Ps17poHz9P7J7YTzFDPWdOZQgj6Yb7fk4dWT0sJPzJfDsPLGr7e9IBeJ9oSFBUdoELePMKIsS/GvWoSwO2f7FOGruPjVHpRBf14YfAqGpf64sYZ0W7u6Kc4vy9Cc7ROg3L3+fLVaHfGrYRtUB4H6UF+wC1cFh3IO2bsT2MSKkL9Wv5DausjPNuCtt9nHo8zKxVvp0sCai1MA1HZWOlRWa8dzPWZw==
              runcmd:
                - systemctl enable --now qemu-guest-agent
                - systemctl enable --now docker
                - systemctl enable --now fstrim.timer
                - systemctl set-default graphical.target
                - systemctl enable --now lightdm
  dataVolumeTemplates:
    - metadata:
        name: sandbox-rootdisk
      spec:
        storage:
          resources:
            requests:
              storage: 100Gi
          storageClassName: blueberry-nfs-kubevirt
        source:
          http:
            url: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2