apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blueberry-nfs-kubevirt
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.182
  share: /mnt/cronenberg/nfs/kubevirt
  mountPermissions: "0"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true