apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflared
  namespace: cloudflare
spec:
  interval: 1h0m0s
  path: ./apps/services/cloudflare//app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
