---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: ollama
spec:
  chart:
    spec:
      chart: open-webui
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: open-webui
  interval: 1m0s
  releaseName: open-webui
  values:
    ollama:
      enabled: false
    service:
      type: ClusterIP
    ollamaUrls:
      - http://ollama.ollama.svc.cluster.local:11434
    # ingress:
    #   enabled: true
    #   class: traefik
    #   # -- Use appropriate annotations for your Ingress controller, e.g., for NGINX:
    #   # nginx.ingress.kubernetes.io/rewrite-target: /
    #   annotations: {}
    #   host: chat.internal
    #   tls: true
    #   existingSecret: selfsigned-tls