apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - namespace.yaml
  - ipaddresspool.yaml
  - l2advertisement.yaml
  - https://github.com/metallb/metallb/blob/main/charts/metallb/charts/crds/templates/crds.yaml