---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
spec:
  chart:
    spec:
      chart: operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: minio-operator
  interval: 1m0s
  values:
    operator:
      env:
        - name: OPERATOR_STS_AUTO_TLS_ENABLED
          value: "off"
        - name: OPERATOR_STS_ENABLED
          value: "on"