---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/v1nsai/jellyfin-helm
