---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  chart:
    spec:
      chart: ./charts/jellyfin
      sourceRef:
        kind: GitRepository
        name: jellyfin
        namespace: jellyfin
  interval: 1m0s
  values:
    persistence:
      config:
        enabled: true
        # storageClass: microk8s-hostpath
      media:
        enabled: true
        existingClaim: media-pvc
        accessMode: ReadWriteMany
    extraEnvVars:
      - name: NVIDIA_VISIBLE_DEVICES
        value: "all"
      - name: NVIDIA_DRIVER_CAPABILITIES
        value: "all"
      - name: DOTNET_SYSTEM_IO_DISABLEFILELOCKING
        value: "true"
    extraPodLabels:
      backup.velero.io/backup-volumes-excludes: "media-pvc"
      velero.io/exclude-from-backup: "true"
    # nodeSelector:
    #   nvidia.com/gpu.present: "true"
