apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: jellyfin
spec:
  storageClassName: irma-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2600Gi
