apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    log:
      level: INFO

    api:
      dashboard: false
      insecure: false

    entryPoints:
      web:
        address: :80
      websecure:
        address: :443

    certificatesResolvers:
      letsencrypt-prod:
        acme:
          email: support@techig.com
          storage: /acme.json
          httpChallenge:
            entryPoint: web

      letsencrypt-staging:
        acme:
          email: support@techig.com
          storage: /acme.json
          caserver: https://acme-staging-v02.api.letsencrypt.org/directory
          httpChallenge:
            entryPoint: web
