---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8up
  namespace: k8up
spec:
  interval: 1h0m0s
  path: ./projects/k8up/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
