---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvdp
spec:
  chart:
    spec:
      chart: nvidia-device-plugin
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nvdp
  interval: 1m0s
  values:
    runtimeClassName: nvidia