---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: opensearch-auth
  namespace: opensearch
spec:
  encryptedData:
    OPENSEARCH_INITIAL_ADMIN_PASSWORD: AgDrM956nmGb5gdeL/t49aTSC6K0DldS4g3DoawZA1/10co4kIDScpGv8TFNEvM392/x30ulqGY0nDBtYAWqbj69KegBG0YGiXVFLLRwBnY+UXvLGtIybDQFYBoXPGZGDgGP1Tza6v0CWisFwzljjVyyG1SxS7F/tHf7fNHEsrpcIHaCHvDuDwChVI1C7euudk9b1fy/OSK9F+ULQppxLLkhBiATdUAD1Cij8qRA9zjGt+tpgi7MARiBxlYBQMpQNSodkTJ/XGvSteB1Mx5TgKUt5VPQCwEJC13EJK8tgJ7OxRN8xUQMbmdywnlzpe95btxq+X33v1iZSEM70N+ZreCjjIlzyW23EwbMOwrBe/+Dz3X/XFYhOANIP8QAow+ZKZnfT40/IJNPkRjTQRM+hMF8Trjtc2tpbvanir1jPyb7C7sG2ScLo2XsgCs+WS2Wl3k8BlEr6LJjwQWXM1XfztERn/g1IHib87Vyp+9kO66Wrzi+BHwlxZ25r+UQH6GjhAvsc7MuLKZ2vfyPDzJfh9rCdjiCAuoaKJZVk/dMHRnHez/OwH0fjE1x8BSggG1MQNhfKwBybpjmWljNk++Op4I03sYdS6TZbxK39v2mnWynB7INt7q/ZR1r1FA3GXHehxqrMsXnh23XM4/X/OzDH8Oyq4PrnKEvNiirufQ4MQLIJ3/PwjW6ttb2thyPMFFK2HLP4ePKdQOdCTo+CULyYjAlXPRHSlC6z5dXMLTK
  template:
    metadata:
      name: opensearch-auth
      namespace: opensearch
