---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
spec:
  chart:
    spec:
      chart: airflow
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
  interval: 1h0m0s
  releaseName: airflow
  values:
    executor: KubernetesExecutor
    workers:
      # serviceAccount:
      #   create: true
      extraVolumes:
        - name: spark-scripts
          configMap:
            name: spark-scripts
      extraVolumeMounts:
        - name: spark-scripts
          mountPath: /opt/spark/scripts
    dags:
      gitSync:
        enabled: true
        repo: https://github.com/v1nsai/homelab
        branch: develop
        rev: HEAD
        subPath: apps/data-science/airflow/dags
        # depth: 1
    webserverSecretKeySecretName: webserver-secret
    webserverSecretKey: webserver-secret