apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: airflow
  namespace: airflow
resources:
  - ./helmrelease.yaml
  - ./helmrepository.yaml
  - ./sealed-secret-values.yaml
  - ./sealed-secrets.yaml
