---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webserver-secret
  namespace: airflow
spec:
  encryptedData:
    webserver-secret-key: AgCq2CZjEVdRc4adMmA8qFACw2i6LciqSNR+6UqQ2cv0eMOEpoZydyJVrfhY6qMIhTRSFK6clsJsHqjU5HgeLOLehWs6DZUcbRrkvmud4y5LdWmzMj0CCSdll3Ni0iBuDISIZYYtH1IPoKywdbe6oFHCOWomMy+De3VLb6iP3BH6IXTkAvC/j9tnIRWN2XrbccnBJptuudYeuK+qEMNepfcb9qyTwiPcrhpZKI2kMmu/eKWAnVEm9aoE1JYyl+pXYmNpJfwOFgc79Ek2lgnfWDs7z+3UvAXmN5J53Axnm93T6xSbnjV6KZLKdgDNalzUdzl53/M/REy9waRk38RgyHe5SBCimvAq1vbKJkaNy8TE/rmOXrjaFkXEhtcmx0uiCrneVmOhfx4QaSrwmDqBfPyRSDkSVZnF75YliNzlGq/uG6q+eYckBcJs+CR9uUSTpyrWTX5CcIXi9XL2Z6ixuSyuLVkrsfOllB9wPtLuEiMVb5fewdLzJl/7yp/xWPxKaeYjp8D5SkGmSe1r+luGAbTlbLJKX5QZKMFBH+xRpZ+EZ7hu9ZHuft9cHmtn/9hvQthdEfTOzsWlqc9NyYsAFldl5RtuoIhSCRrh5XXCFnF9G3oMGL8UKMV+YUrWk6M9XsjQFy74ilxsW6PpaiMFTgwMU+mDkQAG05eQWOBLPKux5HOIXRLAEnpKsBsSBaqWvD+wJXavg1TIisLLG8kGRkyg/c2BjeeRw96HGOeOe4kNxpkuTUyPLg5Zl8RehA==
  template:
    metadata:
      creationTimestamp: null
      name: webserver-secret
      namespace: airflow
