---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blueberry-nfs
spec:
  chart:
    spec:
      chart: csi-driver-nfs
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
  interval: 1h0m0s
  targetNamespace: blueberry-nfs
  values:
    # kubeletDir: /var/snap/microk8s/common/var/lib/kubelet
    controller:
      dnsPolicy: ClusterFirstWithHostNet
      # runOnControlPlane: true
    node:
      dnsPolicy: ClusterFirstWithHostNet
    storageClass:
      create: true
      name: blueberry-nfs
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
      parameters:
        server: 192.168.1.182
        share: /mnt/cronenberg/nfs
        mountPermissions: "0"
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      mountOptions:
        - nfsvers=4.2
    # externalSnapshotter:
    #   enabled: false
    #   name: snapshot-controller