---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: flux-system
spec:
  chart:
    spec:
      chart: rook-ceph-cluster
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rook-release
  interval: 1h0m0s
  values:
    clusterName: rook-ceph-cluster
    toolbox:
      enabled: true
      containerSecurityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
    monitoring:
      enabled: true
      createPrometheusRules: true
    cephClusterSpec:
      # Important: if you reinstall the cluster, make sure you delete this directory from each host or else the mons will fail to start on the new cluster.
      dataDirHostPath: /var/lib/rook
      # TODO experiement with these to see if performance improves without issues
      network:
        encryption:
          enabled: "false"
        compression:
          enabled: "false"
      storage:
        # config:
        #   osdsPerDevice: 3
        nodes:
          - name: bigrig
            devices:
              - name: "/dev/sdb"
              - name: "/dev/sdc"
          - name: oppenheimer
            devices:
              - name: "/dev/sdc"
    cephFileSystemVolumeSnapshotClass:
      enabled: true
    cephBlockPoolsVolumeSnapshotClass:
      enabled: true
    cephBlockPools:
    - name: ceph-blockpool
      storageClass:
        isDefault: false
        enabled: true
        parameters:
          archiveOnDelete: "true"
    cephFileSystems:
    - name: ceph-filesystem
      storageClass:
        name: cephfs
        isDefault: false
        enabled: true
        parameters:
          archiveOnDelete: "true"
    cephObjectStores:
    - name: ceph-objectstore
      storageClass:
        isDefault: false
        enabled: true
        parameters:
          archiveOnDelete: "true"