---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ollama
  namespace: ollama
spec:
  interval: 1m0s
  path: ./projects/ollama/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: open-webui
  namespace: ollama
spec:
  interval: 1m0s
  path: ./projects/ollama/ui
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
