---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ollama
  namespace: ollama
spec:
  interval: 1m0s
  path: ./ollama
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
