# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: opensearch
  namespace: opensearch
spec:
  interval: 10m0s
  path: ./apps/data-science/opensearch/opensearch
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  targetNamespace: opensearch
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: opensearch-dashboards
  namespace: opensearch
spec:
  interval: 10m0s
  path: ./apps/data-science/opensearch/opensearch-dashboards
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  targetNamespace: opensearch