apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - https://github.com/cert-manager/cert-manager//deploy/crds
  - issuers.yaml