---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./cluster/addons/local-path-provisioner/app/
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
