---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 1h0m0s
  path: ./apps/services/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  timeout: 3m0s
  wait: true
