---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: irma-nfs
  namespace: irma-nfs
spec:
  interval: 1h0m0s
  path: ./projects/nfs/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
