# # nfs
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: nfs-csi
# provisioner: nfs.csi.k8s.io
# parameters:
#   server: 192.168.1.214
#   share: /mnt/k8s_volumes
# reclaimPolicy: Delete
# volumeBindingMode: Immediate
# mountOptions:
#   - hard
#   - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blackbox-nfs-pvc
  namespace: plex
spec:
  accessModes: [ReadWriteOnce]
  resources: 
    requests: 
      storage: 5Gi
  storageClassName: nfs-client