apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-creator-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-creator
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["create", "get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-creator-binding
subjects:
- kind: ServiceAccount
  name: secret-creator-sa
roleRef:
  kind: Role
  name: secret-creator
  apiGroup: rbac.authorization.k8s.io