---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin
resources:
  - ./deployment.yaml
  - ./pvc.yaml
  - ./service.yaml
  - ./wireguard-config-sealed.yaml