version: "2.1"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    ports:
      - 51820:51820/udp
      - 9091:9091
      - 8112:8112
      - 6881:6881
      - 9696:9696
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
    volumes:
      - ./config/gluetun/wg0.conf:/gluetun/wireguard/wg0.conf

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=9091
    volumes:
      - ./config/qbittorrent:/config
      - /mnt/silverstick/kubernetes/plex-media:/downloads
      - /mnt/silverstick/kubernetes/calibre-media:/books
    restart: unless-stopped
    network_mode: service:gluetun

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./projects/torrents/config/prowlarr:/config
    restart: unless-stopped
    network_mode: service:gluetun

