apiVersion: apps/v1
kind: Deployment
metadata:
  name: torrents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: torrents
  template:
    metadata:
      labels:
        app: torrents
    spec:
      containers:
        - name: gluetun
          image: qmcgaw/gluetun:latest
          imagePullPolicy: Always
          env:
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "192.168.1.0/24,10.0.0.0/8,172.16.0.0/12"
            - name: VPN_PORT_FORWARDING
              value: "on"
            - name: VPN_PORT_FORWARDING_PROVIDER
              value: "protonvpn"
            - name: VPN_SERVICE_PROVIDER
              value: "custom"
            - name: VPN_TYPE
              value: "wireguard"
            - name: TZ
              value: "America/New_York"
            - name: FIREWALL_INPUT_PORTS
              value: "9091,9696,8989"
          ports:
            - containerPort: 51820
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          volumeMounts:
            - name: wg-config
              mountPath: /gluetun/wireguard/

        - name: qbittorrent
          image: linuxserver/qbittorrent
          env:
            - name: WEBUI_PORT
              value: "9091"
          ports:
            - containerPort: 9091
          volumeMounts:
            - name: downloads
              mountPath: /downloads
            - name: qbittorrent-config
              mountPath: /config

        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
          ports:
            - containerPort: 9696
          volumeMounts:
            - name: prowlarr-config
              mountPath: /config
        
        - name: sonarr
          image: lscr.io/linuxserver/sonarr
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
          ports:
            - containerPort: 8989
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: downloads
              mountPath: /tv
              subPath: tv
            # - name: downloads
            #   mountPath: /downloads
            #   subPath: sonarr-downloads

      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: the-goods
        - name: wg-config
          secret:
            secretName: wireguard-config
            items:
              - key: wg0.conf
                path: wg0.conf
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: prowlarr-config
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-config
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  type: LoadBalancer
  ports:
    - name: "9091"
      port: 9091
      targetPort: 9091
  selector:
    app: torrents
# service for prowlarr
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
spec:
  type: LoadBalancer
  ports:
    - name: "9696"
      port: 9696
      targetPort: 9696
  selector:
    app: torrents
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  type: LoadBalancer
  ports:
    - name: "8989"
      port: 8989
      targetPort: 8989
  selector:
    app: torrents
# # pvcs commented out to persist between installations
# ---
# kubectl apply -n jellyfin -f - <<EOF
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: qbittorrent-config
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: prowlarr-config
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
# EOF
# ---
# kubectl apply -f - <<EOF
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: sonarr-config
#   namespace: jellyfin
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
# EOF