---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: irma-nfs
spec:
  interval: 1h0m0s
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
