services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    # security_opt:
    #   - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - PASSWORD=${CALIBRE_PASSWORD}
      # - CLI_ARGS= #optional
    volumes:
      - calibre_config:/config
      - calibre_web_media:/books
    ports:
      - 8080:8080
      - 8181:8181
      - 8081:8081
      - 9090:9090
    restart: unless-stopped

  # calibre-web:
  #   image: lscr.io/linuxserver/calibre-web:latest
  #   container_name: calibre-web
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/New_York
  #     - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
  #     - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
  #   volumes:
  #     - calibre_web_config:/config
  #     - calibre_web_media:/books
  #   ports:
  #     - 8083:8083
  #   restart: unless-stopped

volumes:
  calibre_config:
  # calibre_web_config:
  calibre_web_media:
