services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    # security_opt:
    #   - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - PASSWORD=${CALIBRE_PASSWORD}
      # - CLI_ARGS= #optional
    volumes:
      - calibre_config:/config
      - calibre_web_media:/books
    ports:
      - 8080:8080
      - 8181:8181
      - 8081:8081
      - 9090:9090
    restart: unless-stopped

volumes:
  calibre_config:
  calibre_web_media:
