---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/v1nsai/homelab
  ref:
    branch: develop
  ignore: |
    values.yaml