server:
  service:
    type: LoadBalancer
  autoscaling:
    enabled: true
    minReplicas: 2
    
redis-ha:
  enabled: true

controller:
  replicas: 1

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicas: 2

configs:
  params:
    application:
      namespaces: "*"

application:
  resourceTrackingMethod: "annotation+label"