version: '3.8'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3030:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana_dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana_datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      # - ./grafana.ini:/etc/grafana/grafana.ini
      - ./node-exporter-dashboard.json:/var/lib/grafana/dashboards/node-exporter-dashboard.json
      - ./blackbox-exporter-dashboard.json:/var/lib/grafana/dashboards/blackbox-exporter-dashboard.json
    networks:
      - monitoring

  blackbox_exporter:
    ports:
      - 9115
    container_name: blackbox_exporter
    volumes:
      - './blackbox.yml:/config/blackbox.yml'
    image: 'quay.io/prometheus/blackbox-exporter:latest'
    command: '--config.file=/config/blackbox.yml'
    networks:
      - monitoring
    restart: unless-stopped