global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx] 
    static_configs:
      - targets:
        - https://somewhere.host.com
        - https://nextcloud.somewhere.host.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115 

  - job_name: 'blackbox_exporter'
    static_configs:
      - targets: ['blackbox_exporter:9115']

remote_write:
  - url: 'https://grafana:3000'
    basic_auth:
      username: 'admin'
      password: 'grafana'