---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 1m0s
  targetNamespace: cert-manager
  path: ./cluster/addons/cert-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system