---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jenkins
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/services/jenkins/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system