---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: jellyfin
  path: ./projects/jellyfin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: jellyfin
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
