# pms:
#   resources:
#     limits:
#       nvidia.com/gpu: 1
extraVolumeMounts:
  - name: cronenberg
    mountPath: /cronenberg
extraVolumes:
  - name: cronenberg
    nfs:
      server: 192.168.1.182
      path: /mnt/cronenberg
extraEnv:
  NVIDIA_VISIBLE_DEVICES: "all"
  NVIDIA_DRIVER_CAPABILITIES: "all"
image:
  pullPolicy: Always
service:
  type: LoadBalancer
