---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  chart:
    spec:
      chart: nextcloud
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nextcloud
  interval: 1m0s
  timeout: 15m
  values:
    cronjob:
      enabled: true
    externalDatabase:
      enabled: true
      existingSecret:
        enabled: true
        passwordKey: mariadb-password
        secretName: mariadb-passwords
        usernameKey: mariadb-username
    internalDatabase:
      enabled: false
    livenessProbe:
      initialDelaySeconds: 1800
    mariadb:
      auth:
        existingSecret: mariadb-passwords
      enabled: true
      primary:
        persistence:
          enabled: true
    nextcloud:
      phpConfigs:
        redis-cluster.ini: |-
          session.save_handler = rediscluster
          session.save_path = "seed[]=redis-cluster-endpoint&timeout=2&read_timeout=2&failover=error&persistent=1&auth[user]=redis-user&auth[pass]=redis-password"
          redis.session.locking_enabled=1
          redis.session.lock_retries=-1
          redis.session.lock_wait_time=10000
      configs:
        redis-cluster.config.php: |-
          <?php 
          $CONFIG = [
            'memcache.distributed' => '\\OC\\Memcache\\Redis',
            'memcache.locking' => '\\OC\\Memcache\\Redis',
            'redis.cluster' => [
              'seeds' => [
                'redis-cluster-endpoint',
              ],
              'timeout' => 0.0,
              'read_timeout' => 0.0,
              'failover_mode' => \RedisCluster::FAILOVER_ERROR,
              'user' => 'redis-user',
              'password' => 'redis-password'
            ],
          ];
        mycustom.config.php: |
          <?php
          $CONFIG = array(
            'trusted_proxies' => array('10.0.0.0/8'),
            'default_phone_region' => 'US',
            'maintenance_window_start' => 1,
            );
      existingSecret:
        secretName: nextcloud-admin
    persistence:
      enabled: true
      nextcloudData:
        enabled: true
    readinessProbe:
      initialDelaySeconds: 1800
    redis:
      auth:
        enabled: false
        existingSecret: redis-password
        existingSecretKey: redis-password
      enabled: true
    service:
      type: LoadBalancer
    startupProbe:
      initialDelaySeconds: 1800
