apiVersion: apps/v1
kind: Deployment
metadata:
  name: arr-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servarr
  template:
    metadata:
      labels:
        app: servarr
        backup.velero.io/backup-volumes-excludes: "media-pvc"
        velero.io/exclude-from-backup: "true"
    spec:
      containers:
        - name: prowlarr
          image: ghcr.io/hotio/prowlarr:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
            - name: PROWLARR__PORT
              value: "9696"
            - name: PROWLARR__BIND_ADDRESS
              value: "*"
          ports:
            - containerPort: 9696
          volumeMounts:
            - name: prowlarr-config
              mountPath: /config

        # - name: lidarr
        #   image: ghcr.io/linuxserver/lidarr:latest
        #   imagePullPolicy: Always
        #   env:
        #     - name: PUID
        #       value: "1000"
        #     - name: PGID
        #       value: "1000"
        #     - name: TZ
        #       value: "America/New_York"
        #   ports:
        #     - containerPort: 8686
        #   volumeMounts:
        #     - name: lidarr-config
        #       mountPath: /config

        # - name: flaresolverr
        #   image: ghcr.io/flaresolverr/flaresolverr:latest
        #   imagePullPolicy: Always
        #   env:
        #     - name: TZ
        #       value: "America/New_York"
        #   ports:
        #     - containerPort: 8191

        - name: sonarr
          image: lscr.io/linuxserver/sonarr:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
          ports:
            - containerPort: 8989
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: cronenberg
              mountPath: /downloads

        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
          ports:
            - containerPort: 7878
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: cronenberg
              mountPath: /downloads

        # - name: bazarr
        #   image: lscr.io/linuxserver/bazarr:latest
        #   imagePullPolicy: Always
        #   env:
        #     - name: PUID
        #       value: "1000"
        #     - name: PGID
        #       value: "1000"
        #     - name: TZ
        #       value: "America/New_York"
        #   ports:
        #     - containerPort: 7878
        #   volumeMounts:
        #     - name: bazarr-config
        #       mountPath: /config
        #     - name: cronenberg
        #       mountPath: /downloads

      volumes:
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: prowlarr-config
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-config
        # - name: lidarr-config
        #   persistentVolumeClaim:
        #     claimName: lidarr-config
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config
        # - name: bazarr-config
        #   persistentVolumeClaim:
        #     claimName: bazarr-config
        - name: cronenberg
          nfs:
            server: 192.168.1.182
            path: /mnt/cronenberg