---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflared
  namespace: cloudflare
spec:
  interval: 1h0m0s
  path: ./projects/cloudflared/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
