apiVersion: apps/v1
kind: Deployment
metadata:
  name: devbox
  labels:
    app: devbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devbox
  template:
    metadata:
      labels:
        app: devbox
    spec:
      nodeSelector:
        kubernetes.io/hostname: bigrig
      containers:
      - name: devbox
        image: ubuntu:24.04
        ports:
        - containerPort: 22
        command: ["/bin/sleep", "infinity"]
        volumeMounts:
        - mountPath: /home/ubuntu
          name: devbox-home
        - mountPath: /home/ubuntu/.ssh
          name: ssh-pubkey
          readOnly: true
      volumes:
      - name: devbox-home
        persistentVolumeClaim:
          claimName: devbox-home
      - name: ssh-pubkey
        secret:
          secretName: ssh-pubkey
          secretKey: authorized_keys