apiVersion: apps/v1
kind: Deployment
metadata:
  name: devbox
  labels:
    app: devbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devbox
  template:
    metadata:
      labels:
        app: devbox
    spec:
      nodeSelector:
        kubernetes.io/hostname: bigrig
      containers:
      - name: devbox
        # image: ubuntu:24.04
        image: docker:dind
        securityContext:
          privileged: true
        # lifecycle:
        #   postStart:
        #     exec:
        #       command: ["/bin/bash", "-c", "/postinstall.sh"]
        environment:
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: ssh-pubkey
                key: username
        ports:
        - containerPort: 22
        command: ["/bin/sleep", "infinity"]
        volumeMounts:
        - mountPath: /home
          name: devbox-home
        - mountPath: /authorized_keys
          name: ssh-pubkey
          readOnly: true
        - mountPath: /postinstall.sh
          name: postinstall
          readOnly: true
      volumes:
      - name: devbox-home
        persistentVolumeClaim:
          claimName: devbox-home
      - name: ssh-pubkey
        secret:
          secretName: ssh-pubkey
          secretKey: authorized_keys
      - name: postinstall
        configMap:
          name: postinstall
          items:
            - key: postinstall.sh
              path: postinstall.sh
