---
apiVersion: v1
kind: Service
metadata:
  name: devbox
spec:
  type: LoadBalancer
  ports:
    - name: "ssh"
      port: 22
      targetPort: 22
    - name: "http"
      port: 80
      targetPort: 80
    - name: "https"
      port: 443
      targetPort: 443
    - name: "node"
      port: 3000
      targetPort: 3000
    - name: "misc-tcp"
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: "misc-udp"
      port: 8080
      protocol: UDP
      targetPort: 8080
  selector:
    app: devbox
