---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-tenant
spec:
  chart:
    spec:
      chart: tenant
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: minio-operator
  interval: 1m0s
  values:
    secrets: {}
    tenant:
      name: homelab-minio
      configSecret:
        name: user-config
        existingSecret: true