---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-tenant
spec:
  chart:
    spec:
      chart: tenant
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: minio-operator
  interval: 1m0s
  valuesFrom:
    - kind: Secret
      name: secret-values
      valuesKey: secret-values.yaml
  values:
    tenant:
      name: homelab-minio
      # configSecret: # TODO rm once https://github.com/minio/operator/pull/2284 is fixed
      #   name: user-config
      #   existingSecret: true
