apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Drew's Cool Shit
    background: slate
    theme: dark
    color: cyan
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: "" # |
    # - Home:
    #   - HomeAssistant:
    #       - abbr: hass
    #         href: http://home-assistant.internal:8123
    #   - Homepage Documentation
    #       - abbr: HD
    #         href: https://gethomepage.dev/latest/configs/
  services.yaml: |
    - Home:
        - HomeAssistant:
            href: http://home-assistant.internal:8123
            description: HomeAssistant Dashboard
        - Homepage Documentation
            href: https://gethomepage.dev/latest/configs/
            description: Homepage Configuration Docs
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: google
        target: _blank
  docker.yaml: ""