apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2600Gi
  storageClassName: csi-cephfs-sc