kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-ceph
  labels:
    vol: pvc-ceph
  namespace: default
spec:
  storageClassName: ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
