---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wordpress
  namespace: personal-site
spec:
  interval: 1m0s
  path: ./projects/personal-site/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
